# Mediation Analysis 

When we have estimated the treatment effect of a program, we sometimes wonder by which channels the program impact has been obtained.
For example, has a Job Training Program been successful because it has increases the human capital of an agent, or simply by signalling to employers her motivation?
The question of separating between the various channels into which a program impact can be decomposed becomes especially important when a program has several components, and we wish to ascertain which one is the more important. 
Another reason why we might be interested in which channel precisely is responsible for the program impact is because which channel dominates might give us indications about which theoretical mechanism is at play.

In this chapter, I am going to first delineate the general framework for mediation analysis and the way mediation analysis can be undertaken in the ideal case of a Randomized Controlled Trial.
Then, I am going to present the fundamental problem of mediation analysis (which turns out to be one version of the confounders problem we know all too well) and the various techniques that have been developed in order to solve for it.

## Mediation analysis: a framework



## The Fundamental Problem of Mediation Analysis

## Mediation analysis under unconfoundedness

## Mediation analysis with panel data

## Mediation analysis with instruments
