# (APPENDIX) Appendix {-}

# Proofs 

## Proofs of results in Chapter \@ref(FPSI)

### Proof of Theorem \@ref(thm:uppsampnoise) {#proofcheb}

In order to use Theorem \@ref(thm:cheb) for studying the behavior of $\hat{\Delta^Y_{WW}}$, we have to prove that it is unbiased and we have to compute $\var{\hat{\Delta^Y_{WW}}}$.
Let's first prove that the $WW$ estimator is an unbiased estimator of $TT$:

```{lemma,unbiasww,name="Unbiasedness of $\\hat{\\Delta^Y_{WW}}$"}
Under Assumptions \@ref(def:noselb), \@ref(hyp:fullrank) and \@ref(hyp:iid),

\begin{align*}
\esp{\hat{\Delta^Y_{WW}}}& = \Delta^Y_{TT}.
\end{align*}

```

```{proof}
In order to prove Lemma \@ref(lem:unbiasww), we are going to use a trick.
We are going to compute the expectation of the $WW$ estimator conditional on a given treatment allocation.
Because the resulting estimate is independent of treatment allocation, we will have our proof. 
This trick simplifies derivations a lot and is really natural: think first of all the samples with the same treatment allocation, then average your results over all possible treatment allocations.

\begin{align*}
\esp{\hat{\Delta^Y_{WW}}} & = \esp{\esp{\hat{\Delta^Y_{WW}}|\mathbf{D}}}\\
                          & = \esp{\esp{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N Y_iD_i-\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}}\\
                          & = \esp{\esp{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N Y_iD_i|\mathbf{D}}-\esp{\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}}\\
                          & = \esp{\frac{1}{\sum_{i=1}^N D_i}\esp{\sum_{i=1}^N Y_iD_i|\mathbf{D}}-\frac{1}{\sum_{i=1}^N (1-D_i)}\esp{\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}}\\
                          & = \esp{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N \esp{Y_iD_i|\mathbf{D}}-\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N \esp{Y_i(1-D_i)|\mathbf{D}}}\\
                          & = \esp{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N \esp{Y_iD_i|D_i}-\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N \esp{Y_i(1-D_i)|D_i}}\\
                          & = \esp{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N D_i\esp{Y_i|D_i=1}-\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N(1-D_i)\esp{Y_i|D_i=0}}\\
                          & = \esp{\frac{\sum_{i=1}^N D_i}{\sum_{i=1}^N D_i}\esp{Y_i|D_i=1}-\frac{\sum_{i=1}^N(1-D_i)}{\sum_{i=1}^N (1-D_i)}\esp{Y_i|D_i=0}}\\
                          & = \esp{\esp{Y_i|D_i=1}-\esp{Y_i|D_i=0}}\\
                          & = \esp{Y_i|D_i=1}-\esp{Y_i|D_i=0} \\
                          & = \Delta^Y_{TT}.
\end{align*}

The first equality uses the Law of Iterated Expectations (LIE).
The second and fourth equalities use the linearity of conditional expectations.
The third equality uses the fact that, conditional on $\mathbf{D}$, the number of treated and untreated is a constant.
The fifth equality uses Assumption \@ref(hyp:iid).
The sixth equality uses the fact that $\esp{Y_iD_i|D_i}=D_i\esp{Y_i*1|D_i=1}+(1-D_i)\esp{Y_i*0|D_i=0}$.
The seventh and ninth equalities use the fact that $\esp{Y_i|D_i=1}$ is a constant.
The last equality uses Assumption \@ref(def:noselb).

```

Let's now compute the variance of the $WW$ estimator:

```{lemma,varww,name="Variance of $\\hat{\\Delta^Y_{WW}}$"}
Under Assumptions \@ref(def:noselb), \@ref(def:fullrank) and \@ref(hyp:iid), 

\begin{align*}
\var{{\hat{\Delta^Y_{WW}}}} & = \frac{1-(1-\Pr(D_i=1))^N}{N\Pr(D_i=1)}\var{Y_i^1|D_i=1}+\frac{1-\Pr(D_i=1)^N}{N(1-\Pr(D_i=1))}\var{Y_i^0|D_i=0}.
\end{align*}

```

```{proof}
Same trick as before, but now using the Law of Total Variance (LTV):
  
\begin{align*}
\var{{\hat{\Delta^Y_{WW}}}} & = \esp{\var{\hat{\Delta^Y_{WW}}|\mathbf{D}}}+\var{\esp{\hat{\Delta^Y_{WW}}|\mathbf{D}}}\\
                            & = \esp{\var{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N Y_iD_i-\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}} \\
                            & = \esp{\var{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N Y_iD_i|\mathbf{D}}}+\esp{\var{\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}}\\
                            & \phantom{=}+\esp{\cov{\frac{1}{\sum_{i=1}^N D_i}\sum_{i=1}^N Y_iD_i,\frac{1}{\sum_{i=1}^N (1-D_i)}\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}} \\
                            & = \esp{\frac{1}{(\sum_{i=1}^N D_i)^2}\var{\sum_{i=1}^N Y_iD_i|\mathbf{D}}}+\esp{\frac{1}{(\sum_{i=1}^N (1-D_i))^2}\var{\sum_{i=1}^N Y_i(1-D_i)|\mathbf{D}}} \\
                            & = \esp{\frac{1}{(\sum_{i=1}^N D_i)^2}\var{\sum_{i=1}^N Y_iD_i|D_i}}+\esp{\frac{1}{(\sum_{i=1}^N (1-D_i))^2}\var{\sum_{i=1}^N Y_i(1-D_i)|D_i}} \\
                            & = \esp{\frac{1}{(\sum_{i=1}^N D_i)^2}\sum_{i=1}^ND_i\var{Y_i|D_i=1}}+\esp{\frac{1}{(\sum_{i=1}^N (1-D_i))^2}\sum_{i=1}^N(1-D_i)\var{Y_i|D_i=0}} \\
                            & = \var{Y_i|D_i=1}\esp{\frac{1}{\sum_{i=1}^N D_i}}+\var{Y_i|D_i=0}\esp{\frac{1}{\sum_{i=1}^N (1-D_i)}} \\
                            & = \frac{1-(1-\Pr(D_i=1))^N}{N\Pr(D_i=1)}\var{Y_i^1|D_i=1}+\frac{1-\Pr(D_i=1)^N}{N(1-\Pr(D_i=1))}\var{Y_i^0|D_i=0}.
\end{align*}

The first equality stems from the LTV.
The second and third equalities stems from the definition of the $WW$ estimator and of the variance of a sum of random variables.
The fourth equality stems from Assumption \@ref(hyp:iid), which means that the covariance across observations is zero, and from the formula for a variance of a random variable multiplied by a constant.
The fifth and sixth equalities stems from Assumption \@ref(hyp:iid) and from $\var{Y_iD_i|D_i}=D_i\var{Y_i*1|D_i=1}+(1-D_i)\var{Y_i*0|D_i=0}$.
The seventh equality stems from $\var{Y_i|D_i=1}$ and $\var{Y_i|D_i=0}$ being constant.
The last equality stems from the formula for the expectation of the inverse of a sum of Bernoulli random variables with at least one of them taking value one which is the case under Assumption \@ref(hyp:fullrank).
```

Using Theorem \@ref(thm:cheb), we have:

\begin{align*}
2\epsilon & \leq 2\sqrt{\frac{1}{N(1-\delta)}\left(\frac{1-(1-\Pr(D_i=1))^N}{\Pr(D_i=1)}\var{Y_i^1|D_i=1}+\frac{1-\Pr(D_i=1)^N}{(1-\Pr(D_i=1))}\var{Y_i^0|D_i=0}\right)}\\
          & \leq 2\sqrt{\frac{1}{N(1-\delta)}\left(\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{(1-\Pr(D_i=1))}\right)},
\end{align*}

where the second equality stems from the fact that $\frac{(1-\Pr(D_i=1))^N}{\Pr(D_i=1)}\var{Y_i^1|D_i=1}+\frac{\Pr(D_i=1)^N}{(1-\Pr(D_i=1))}\var{Y_i^0|D_i=0}\geq0$.
This proves the result.

### Proof of Theorem \@ref(thm:asympnoiseWW) {#proofCLT}

Before proving Theorem \@ref(thm:asympnoiseWW), let me state a very useful result: $\hat{WW}$ can be computed using OLS:

```{lemma,WWOLS,name="WW is OLS"}
Under Assumption \@ref(hyp:fullrank), the OLS coefficient $\beta$ in the following regression: 

\begin{align*}
		Y_i &  = \alpha +  \beta D_i + U_i
	\end{align*}

is the WW estimator:

\begin{align*}
\hat{\beta}_{OLS} & = \frac{\frac{1}{N}\sum_{i=1}^N\left(Y_i-\frac{1}{N}\sum_{i=1}^NY_i\right)\left(D_i-\frac{1}{N}\sum_{i=1}^ND_i\right)}{\frac{1}{N}\sum_{i=1}^N\left(D_i-\frac{1}{N}\sum_{i=1}^ND_i\right)^2} \\
  								& = \hat{\Delta^Y_{WW}}.
\end{align*}

```

```{proof}
In matrix notation, we have:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_1 \\	\vdots \\	Y_N \end{array}\right)}_{Y} & = 
  \underbrace{\left(\begin{array}{cc}	1 & D_1\\	\vdots & \vdots\\	1 & D_N\end{array}\right)}_{X}
  \underbrace{\left(\begin{array}{c}	\alpha \\	\beta \end{array}\right)}_{\Theta}+
  \underbrace{\left(\begin{array}{c}	U_1 \\	\vdots \\	U_N \end{array}\right)}_{U}
\end{align*}

The OLS estimator is:

\begin{align*}
	\hat{\Theta}_{OLS} &  = (X'X)^{-1}X'Y
\end{align*}

Under the Full Rank Assumption, $X'X$ is invertible and we have:

\begin{align*}
(X'X)^{-1} &  = \left(\begin{array}{cc} N & \sum_{i=1}^ND_i \\ \sum_{i=1}^ND_i & \sum_{i=1}^ND_i^2 \end{array}\right)^{-1} \\
                & = \frac{1}{N\sum_{i=1}^ND_i^2-\left(\sum_{i=1}^ND_i\right)^2}\left(\begin{array}{cc} \sum_{i=1}^ND_i^2 & -\sum_{i=1}^ND_i \\ -\sum_{i=1}^ND_i & N \end{array}\right)
\end{align*}

For simplicity, I omit the summation index:

\begin{align*}
  \hat{\Theta}_{OLS} &  = \frac{1}{N\sum D_i^2-\left(\sum D_i\right)^2}
                          \left(\begin{array}{cc} \sum D_i^2 & -\sum D_i \\ -\sum D_i & N \end{array}\right)
                          \left(\begin{array}{c} \sum Y_i \\  \sum Y_iD_i \end{array}\right) \\
                    & = \frac{1}{N\sum D_i^2-\left(\sum D_i\right)^2}
                        \left(\begin{array}{c} \sum D_i^2\sum Y_i-\sum D_i\sum_{i=1}^NY_iD_i \\
                                              -\sum D_i\sum Y_i+ N\sum Y_iD_i \end{array}\right) \\
\end{align*}

Using $D_i^2=D_i$, we have:

\begin{align*}
  \hat{\Theta}_{OLS} &  =  \left(\begin{array}{c} 
          \frac{\left(\sum D_i\right)\left(\sum Y_i-\sum Y_iD_i\right)}{\left(\sum D_i\right)\left(N-\sum D_i\right)} \\
          \frac{N\sum Y_iD_i-\sum D_i\sum Y_i}{N\sum D_i-\left(\sum D_i\right)^2} 
                            \end{array}\right) 
                        =     \left(\begin{array}{c} 
          \frac{\sum (Y_iD_i+Y_i(1-D_i))-\sum Y_iD_i}{\sum(1-D_i)} \\
          \frac{N^2}{N^2}\frac{\frac{1}{N}\sum Y_iD_i-\frac{1}{N}\sum D_i\frac{1}{N}\sum Y_i+\frac{1}{N}\sum D_i\frac{1}{N}\sum Y_i-\frac{1}{N}\sum D_i\frac{1}{N}\sum Y_i}{\frac{1}{N}\sum D_i-2\left(\frac{1}{N}\sum D_i\right)^2+\left(\frac{1}{N}\sum D_i\right)^2} 
                            \end{array}\right) \\
                      &  =     \left(\begin{array}{c} 
          \frac{\sum Y_i(1-D_i)}{\sum(1-D_i)} \\
          \frac{\frac{1}{N}\sum \left(Y_iD_i-D_i\frac{1}{N}\sum Y_i-Y_i\frac{1}{N}\sum D_i+\frac{1}{N}\sum D_i\frac{1}{N}\sum Y_i\right)}{\frac{1}{N}\sum\left(D_i-2D_i\frac{1}{N}\sum D_i+\left(\frac{1}{N}\sum D_i\right)^2\right)} 
                            \end{array}\right) 
                      =     \left(\begin{array}{c} 
          \frac{\sum Y_i(1-D_i)}{\sum(1-D_i)} \\
    \frac{\frac{1}{N}\sum\left(Y_i-\frac{1}{N}\sum Y_i\right)\left(D_i-\frac{1}{N}\sum D_i\right)}{\frac{1}{N}\sum \left(D_i-\frac{1}{N}\sum D_i\right)^2} 
                            \end{array}\right), 
\end{align*}

which proves the first part of the lemma.
Now for the second part of the lemma:

\begin{align*}
  \hat{\beta}_{OLS} &  = \frac{\sum Y_iD_i-\frac{1}{N}\sum D_i\sum Y_i}{\sum D_i\left(1-\frac{1}{N}\sum D_i\right)}
                       = \frac{\sum Y_iD_i-\frac{1}{N}\sum D_i\sum\left(Y_iD_i+(1-D_i)Y_i\right)}{\sum D_i\left(1-\frac{1}{N}\sum D_i\right)}\\
                    &  = \frac{\sum Y_iD_i\left(1-\frac{1}{N}\sum D_i\right)-\frac{1}{N}\sum D_i\sum(1-D_i)Y_i}{\sum D_i\left(1-\frac{1}{N}\sum D_i\right)}\\
                    &  = \frac{\sum Y_iD_i}{\sum D_i}-\frac{\frac{1}{N}\sum(1-D_i)Y_i}{\left(1-\frac{1}{N}\sum D_i\right)}\\
                    &  = \frac{\sum Y_iD_i}{\sum D_i}-\frac{\frac{1}{N}\sum(1-D_i)Y_i}{\frac{1}{N}\sum\left(1-D_i\right)}\\
                     &  = \frac{\sum Y_iD_i}{\sum D_i}-\frac{\sum(1-D_i)Y_i}{\sum\left(1-D_i\right)}\\
                     & = \hat{\Delta^Y_{WW}},
\end{align*}

which proves the result.
```

Now, let me state the most important lemma behind the result in Theorem \@ref(thm:asympnoiseWW):

```{lemma,asympOLS,name="Asymptotic Distribution of the OLS Estimator"}
Under Assumptions \@ref(def:noselb), \@ref(hyp:fullrank), \@ref(hyp:iid) and \@ref(hyp:finitevar), we have:

\begin{align*}
  \sqrt{N}(\hat{\Theta}_{OLS}-\Theta) &  \stackrel{d}{\rightarrow}
  \mathcal{N}\left(\begin{array}{c}	0\\	0\end{array},
  \sigma_{XX}^{-1}\mathbf{V_{xu}}\sigma_{XX}^{-1}\right), 
\end{align*}

with 
\begin{align*}
\sigma_{XX}^{-1}& = \left(\begin{array}{cc}	\frac{\Pr(D_i=1)}{\Pr(D_i=1)(1-\Pr(D_i=1))} & -\frac{\Pr(D_i=1)}{\Pr(D_i=1)(1-\Pr(D_i=1))}\\
                                          -\frac{\Pr(D_i=1)}{\Pr(D_i=1)(1-\Pr(D_i=1))} & \frac{1}{\Pr(D_i=1)(1-\Pr(D_i=1))} 
                          \end{array}\right)\\
\mathbf{V_{xu}}&= \esp{U_i^2\left(\begin{array}{cc}  1 & D_i\\  D_i & D_i\end{array}\right)}                        
\end{align*}

```

```{proof}

\begin{align*}
\sqrt{N}(\hat{\Theta}_{OLS}-\Theta) & = \sqrt{N}((X'X)^{-1}X'Y-\Theta) \\
                                    & = \sqrt{N}((X'X)^{-1}X'(X\Theta+U)-\Theta) \\
                                    & = \sqrt{N}((X'X)^{-1}X'X\Theta+(X'X)^{-1}X'U)-\Theta) \\
                                    & = \sqrt{N}(X'X)^{-1}X'U \\
                                    & = N(X'X)^{-1}\frac{\sqrt{N}}{N}X'U
\end{align*}

Using Slutsky's Theorem, we can study both terms separately.

Before stating Slutsky's Theorem, we need to define a new term: convergence in probability (this is a simpler version of convergence in distribution).
We say that a sequence $X_N$ converges in probability to the constant $x$ if, $\forall\epsilon>0$, $\lim_{N\rightarrow\infty}\Pr(|X_N-x|>\epsilon)=0$.  
We denote $X_N\stackrel{p}{\rightarrow}x$ or $\text{plim}(X_N)=x$.

Slutsky's Theorem states that if $Y_N\stackrel{d}{\rightarrow}y$ and $\text{plim}(X_N)=x$, then:

1. $X_N+Y_N\stackrel{d}{\rightarrow}x+y$
2. $X_NY_N\stackrel{d}{\rightarrow}xy$
3. $\frac{Y_N}{X_N}\stackrel{d}{\rightarrow}\frac{x}{y}$ if $x\neq0$

Using this theorem, we have:

\begin{align*}
\sqrt{N}(\hat{\Theta}_{OLS}-\Theta) & \stackrel{d}{\rightarrow} \sigma_{XX}^{-1}xu,
\end{align*}

Where $\sigma_{XX}^{-1}$ is a matrix of constants and $xu$ is a random variable.

Let's begin with $\frac{\sqrt{N}}{N}X'U\stackrel{d}{\rightarrow}xu$:

\begin{align*}
\frac{\sqrt{N}}{N}X'U & = \sqrt{N}\left(\begin{array}{c}  \frac{1}{N}\sum_{i=1}^{N}U_i\\  \frac{1}{N}\sum_{i=1}^{N}D_iU_i\end{array}\right)
\end{align*}

In order to determine the asymptotic distribution of $\frac{\sqrt{N}}{N}X'U$, we are going to use the vector version of the CLT:

If $X_i$ and $Y_i$ are two i.i.d. random variables with finite first and second moments, we have:

\begin{align*}
	\sqrt{N}
  \left(
	  \begin{array}{c}	
	   \frac{1}{N}\sum_{i=1}^NX_i-\esp{X_i}\\	
	   \frac{1}{N}\sum_{i=1}^NY_i-\esp{Y_i}
	   \end{array}
	 \right) 
      &
  \stackrel{d}{\rightarrow}
  \mathcal{N}
  \left(
    \begin{array}{c}	
    0\\
    0
    \end{array},
  \mathbf{V}
  \right),
\end{align*}

where $\mathbf{V}$ is the population covariance matrix of $X_i$ and $Y_i$.
  
We know that, under Assumption \@ref(def:noselb), both random variables have mean zero: 

\begin{align*}
\esp{U_i}& = \esp{U_i|D_i=1}\Pr(D_i=1)+\esp{U_i|D_i=0}\Pr(D_i=0)=0 \\
\esp{U_iD_i}& = \esp{U_i|D_i=1}\Pr(D_i=1)=0
\end{align*}

Their covariance matrix $\mathbf{V_{xu}}$ can be computed as follows:

\begin{align*}
\mathbf{V_{xu}} & = \esp{\left(\begin{array}{c}  U_i\\	UiD_i\end{array}\right)\left(\begin{array}{cc}	U_i&	UiD_i\end{array}\right)}
                  - \esp{\left(\begin{array}{c}	U_i\\	UiD_i\end{array}\right)}\esp{\left(\begin{array}{cc}	U_i&	UiD_i\end{array}\right)}\\
                & = \esp{\left(\begin{array}{cc}	U_i^2 & U_i^2D_i\\	Ui^2D_i & U_i^2D_i^2\end{array}\right)} 
                  = \esp{U_i^2\left(\begin{array}{cc}	1 & D_i\\	D_i & D_i^2\end{array}\right)} 
                  = \esp{U_i^2\left(\begin{array}{cc}	1 & D_i\\	D_i & D_i\end{array}\right)} 
\end{align*}

Using the Vector CLT, we have that $\frac{\sqrt{N}}{N}X'U\stackrel{d}{\rightarrow}\mathcal{N}\left(\begin{array}{c}  0\\	0\end{array},\mathbf{V_{xu}}\right)$.

Let's show now that $\plims N(X'X)^{-1}=\sigma_{XX}^{-1}$:

\begin{align*}
N(X'X)^{-1} & = \frac{N}{N\sum_{i=1}^ND_i-\left(\sum_{i=1}^ND_i\right)^2}
                \left(\begin{array}{cc} \sum_{i=1}^ND_i & -\sum_{i=1}^ND_i \\ -\sum_{i=1}^ND_i & N \end{array}\right) \\
            & = \frac{1}{N}\frac{1}{\frac{1}{N}\sum_{i=1}^ND_i-\left(\frac{1}{N}\sum_{i=1}^ND_i\right)^2}
                \left(\begin{array}{cc} \sum_{i=1}^ND_i & -\sum_{i=1}^ND_i \\ -\sum_{i=1}^ND_i & N \end{array}\right)\\
            & = \frac{1}{\frac{1}{N}\sum_{i=1}^ND_i-\left(\frac{1}{N}\sum_{i=1}^ND_i\right)^2}
                \left(\begin{array}{cc} \frac{1}{N}\sum_{i=1}^ND_i & -\frac{1}{N}\sum_{i=1}^ND_i \\ -\frac{1}{N}\sum_{i=1}^ND_i & 1 \end{array}\right)\\
\plims N(X'X)^{-1} & = \frac{1}{\plims\frac{1}{N}\sum_{i=1}^ND_i-\left(\plims\frac{1}{N}\sum_{i=1}^ND_i\right)^2}
                \left(\begin{array}{cc} \plims\frac{1}{N}\sum_{i=1}^ND_i & -\plims\frac{1}{N}\sum_{i=1}^ND_i \\ -\plims\frac{1}{N}\sum_{i=1}^ND_i & 1 \end{array}\right)\\
                  & = \frac{1}{\Pr(D_i=1)-\Pr(D_i=1)^2}
                \left(\begin{array}{cc} \Pr(D_i=1) & -\Pr(D_i=1) \\ -\Pr(D_i=1) & 1 \end{array}\right)\\
                 & = \sigma_{XX}^{-1}
\end{align*}

The fourth equality uses Slutsky's Theorem.
The fifth equality uses the Law of Large Numbers (LLN): if $Y_i$ are i.i.d. variables with finite first and second moments, $\plim{N}\frac{1}{N}\sum_{i=1}^NY_i = \esp{Y_i}$.

In order to complete the proof, we have to use the Delta Method Theorem.
This theorem states that: 

\begin{gather*}
  \sqrt{N}(\begin{array}{c}	\bar{X}_N-\esp{X_i}\\	\bar{Y}_N-\esp{Y_i}\end{array})  \stackrel{d}{\rightarrow}\mathcal{N}(\begin{array}{c}	0\\	0\end{array},\mathbf{V}) \\
\Rightarrow \sqrt{N}(g(\bar{X}_N,\bar{Y}_N)-g(\esp{X_i},\esp{Y_i})  \stackrel{d}{\rightarrow}\mathcal{N}(0,G'\mathbf{V}G)
\end{gather*}

where $G(u)=\partder{g(u)}{u}$ and $G=G(\esp{X_i},\esp{Y_i})$.

In our case, $g(xu)=\sigma_{XX}^{-1}xu$, so $G(xu)=\sigma_{XX}^{-1}$.
The results follows from that and from the symmetry of $\sigma_{XX}^{-1}$.
```

A last lemma uses the previous result to derive the asymptotic distribution of $\hat{WW}$:

```{lemma,asymWW,name="Asymptotic Distribution of $\\hat{WW}$"}
Under Assumptions \@ref(def:noselb), \@ref(hyp:fullrank), \@ref(hyp:iid) and \@ref(hyp:finitevar), we have:

\begin{align*}
  \sqrt{N}(\hat{\Delta^Y_{WW}}-\Delta^Y_{TT}) &  \stackrel{d}{\rightarrow}
  \mathcal{N}\left(0,\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}\right).
\end{align*}
```

```{proof}
In order to derive the asymptotic distribution of WW, I use first Lemma \@ref(lem:WWOLS) which implies that the asymptotic distribution of WW is the same as that of $\hat{\beta}_{OLS}$.
Now, from Lemma \@ref(lem:asympOLS), we know that $\sqrt{N}(\hat{\beta}_{OLS}-\beta)\stackrel{d}{\rightarrow}\mathcal{N}(0,\sigma^2_{\beta})$, where $\sigma^2_{\beta}$ is the lower diagonal term of $\sigma_{XX}^{-1}\mathbf{V_{xu}}\sigma_{XX}^{-1}$.
Using the convention $p=\Pr(D_i=1)$, we have:

\begin{align*}
\sigma_{XX}^{-1}\mathbf{V_{xu}}\sigma_{XX}^{-1} 
                  & = \left(\begin{array}{cc}  
                                          \frac{p}{p(1-p)} & -\frac{p}{p(1-p)}\\
                                          -\frac{p}{p(1-p)} & \frac{1}{p(1-p)} 
                          \end{array}\right)
                          \esp{U_i^2\left(\begin{array}{cc}  1 & D_i\\  D_i & D_i\end{array}\right)}        
                          \left(\begin{array}{cc}  
                                          \frac{p}{p(1-p)} & -\frac{p}{p(1-p)}\\
                                          -\frac{p}{p(1-p)} & \frac{1}{p(1-p)} 
                          \end{array}\right)\\
                  & = \frac{1}{(p(1-p))^2}
                          \left(\begin{array}{cc}  
                                          p\esp{U_i^2}-p\esp{U_i^2D_i} & p\esp{U_i^2D_i}-p\esp{U_i^2D_i}\\
                                          -p\esp{U_i^2}+\esp{U_i^2D_i} &  -p\esp{U_i^2D_i}+\esp{U_i^2D_i}
                          \end{array}\right)
                         \left(\begin{array}{cc}  
                                          p & -p\\
                                          -p & 1 
                          \end{array}\right)\\
                 & = \frac{1}{(p(1-p))^2}
                          \left(\begin{array}{cc}  
                                          p^2(\esp{U_i^2}-\esp{U_i^2D_i}) & p^2(\esp{U_i^2D_i}-\esp{U_i^2})\\
                                          p^2(\esp{U_i^2D_i}-\esp{U_i^2}) &  p^2\esp{U_i^2}+(1-2p)\esp{U_i^2D_i}
                          \end{array}\right)
 \end{align*}

The final result comes from the fact that:

\begin{align*}
\esp{U_i^2} & = \esp{U_i^2|D_i=1}p + (1-p)\esp{U_i^2|D_i=0}\\
            & = p\var{Y_i^1|D_i=1}+(1-p)\var{Y_i^0|D_i=0} \\
\esp{U_i^2D_i}  & = \esp{U_i^2|D_i=1}p  \\
                & = p\var{Y_i^1|D_i=1}.
 \end{align*}

As a consequence:

\begin{align*}
\sigma^2_{\beta} &= \frac{1}{(p(1-p))^2}\left(\var{Y_i^1|D_i=1}p(p^2-2p+1) + p^2(1-p)\var{Y_i^0|D_i=0}\right) \\
                  &= \frac{1}{(p(1-p))^2}\left(\var{Y_i^1|D_i=1}p(1-p)^2 + p^2(1-p)\var{Y_i^0|D_i=0}\right)\\
                  & = \frac{\var{Y_i^1|D_i=1}}{p}+\frac{\var{Y_i^0|D_i=0}}{1-p}.
 \end{align*}
```


Using the previous lemma, we can now approximate the confidence level of $\hat{WW}$:

\begin{align*}
\Pr&(|\hat{\Delta^Y_{WW}}-\Delta^Y_{TT}|\leq\epsilon) = \Pr(-\epsilon\leq\hat{\Delta^Y_{WW}}-\Delta^Y_{TT}\leq\epsilon) \\
& = \Pr\left(-\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\leq\frac{\hat{\Delta^Y_{WW}}-\Delta^Y_{TT}}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\leq\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)\\
& \approx \Phi\left(\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)-
\Phi\left(-\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)\\
& = \Phi\left(\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)- 1 + \Phi\left(\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)\\
& = 2\Phi\left(\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)-1.
\end{align*}

As a consequence, 

\begin{align*}
\delta & \approx 2\Phi\left(\frac{\epsilon}{\frac{1}{\sqrt{N}}\sqrt{\frac{\var{Y_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{Y_i^0|D_i=0}}{1-\Pr(D_i=1)}}}\right)-1.
\end{align*}

Hence the result.

## Proofs of results in Chapter \@ref(RCT)

### Proof of Theorem \@ref(thm:IdentLATE) {#proofIdentLATE}

In order to prove the theorem, it is going to be very helpful to prove the following lemma:

```{lemma,UnconfTypes,name='Unconfounded Types'}
Under Assumptions \@ref(def:RandEncouragValid) and \@ref(def:IndepEncourag), the types $T_i$ are independent of the allocation of the treatment: 
  
\begin{align*}
(Y_i^{1,1},Y_i^{0,1},Y_i^{0,0},Y_i^{1,0},T_i)\Ind R_i|E_i=1.
\end{align*}
```

```{proof}
Lemma 4.2 in [Dawid (1979)](https://www.jstor.org/stable/2984718) shows that if $X\Ind Y|Z$ and $U$ is a function of $X$ then $U\Ind Y|Z$.
The fact that $T_i$ is a function of $(D_i^1,D^0_i)$ proves the result.
```

The four sets defined by $T_i$ are a partition of the sample space.
As a consequence, we have (ommitting the conditioning on $E_i=1$ all along for simplicity):

\begin{align*}
\esp{Y_i|R_i=1} & = \esp{Y_i|T_i=a,R_i=1}\Pr(T_i=a|R_i=1)\\
                & \phantom{=}+ \esp{Y_i|T_i=c,R_i=1}\Pr(T_i=c|R_i=1) \\
  							& \phantom{=} + \esp{Y_i|T_i=d,R_i=1}\Pr(T_i=d|R_i=1)\\
  							& \phantom{=} + \esp{Y_i|T_i=n,R_i=1}\Pr(T_i=n|R_i=1)\\
\esp{Y_i|R_i=0} & = \esp{Y_i|T_i=a,R_i=0}\Pr(T_i=a|R_i=0)\\
                & \phantom{=} + \esp{Y_i|T_i=c,R_i=0}\Pr(T_i=c|R_i=0) \\
  							& \phantom{=} + \esp{Y_i|T_i=d,R_i=0}\Pr(T_i=d|R_i=0)\\
  							& \phantom{=}+ \esp{Y_i|T_i=n,R_i=0}\Pr(T_i=n|R_i=0).
\end{align*}

Let's look at all these terms in turn:

\begin{align*}
  \esp{Y_i|T_i=a,R_i=1} & =   \esp{Y_i^{1,1}D_iR_i+Y_i^{1,0}D_i(1-R_i)+Y_i^{0,1}(1-D_i)R_i+Y_i^{0,0}(1-D_i)(1-R_i)|T_i=a,R_i=1} \\
   & =   \esp{Y_i^{1,1}(D^1_iR_i+D_i^0(1-R_i))R_i+Y_i^{0,1}(1-(D^1_iR_i+D_i^0(1-R_i)))R_i|T_i=a,R_i=1} \\
   & =   \esp{Y_i^{1,1}D^1_iR_i^2+Y_i^{0,1}(1-D^1_iR_i)R_i|D_i^1=D_i^0=1,R_i=1} \\
   & =   \esp{Y_i^{1,1}|T_i=a,R_i=1} \\
   & =   \esp{Y_i^{1,1}|T_i=a}, \\
\end{align*}

where the first equality uses Assumption \@ref(def:RandEncouragValid), the second equality uses the fact that $R_i=1$ in the conditional expectation and Assumption \@ref(def:RandEncouragValid), the third equality uses the fact that $R_i=1$, the fourth equality uses the fact that $T_i=a \Leftrightarrow D_i^1=D_i^0=1$ and the last equality uses Lemma \@ref(lem:UnconfTypes).

Using a similar reasoning, we have:

\begin{align*}
  \esp{Y_i|T_i=c,R_i=1} & = \esp{Y_i^{1,1}|T_i=c} \\
  \esp{Y_i|T_i=d,R_i=1} & = \esp{Y_i^{0,1}|T_i=d} \\
  \esp{Y_i|T_i=n,R_i=1} & = \esp{Y_i^{0,1}|T_i=n} \\
  \esp{Y_i|T_i=a,R_i=0} & = \esp{Y_i^{1,0}|T_i=c} \\
  \esp{Y_i|T_i=c,R_i=0} & = \esp{Y_i^{0,0}|T_i=c} \\
  \esp{Y_i|T_i=d,R_i=0} & = \esp{Y_i^{1,0}|T_i=d} \\
  \esp{Y_i|T_i=n,R_i=0} & = \esp{Y_i^{0,0}|T_i=n}.
\end{align*}

Also, Lemma \@ref(lem:UnconfTypes) implies that $\Pr(T_i=a|R_i)=\Pr(T_i=a)$, and the same is true for all other types.
As a consequence, we have:

\begin{align*}
\esp{Y_i|R_i=1} & = \esp{Y_i^{1,1}|T_i=a}\Pr(T_i=a)\\
                & \phantom{=} + \esp{Y_i^{1,1}|T_i=c}\Pr(T_i=c) \\
  							& \phantom{=} + \esp{Y_i^{0,1}|T_i=d}\Pr(T_i=d)\\
  							& \phantom{=} + \esp{Y_i^{0,1}|T_i=n}\Pr(T_i=n)\\
\esp{Y_i|R_i=0} & = \esp{Y_i^{1,0}|T_i=a}\Pr(T_i=a)\\
                & \phantom{=} + \esp{Y_i^{0,0}|T_i=c}\Pr(T_i=c) \\						
								& \phantom{=} + \esp{Y_i^{1,0}|T_i=d}\Pr(T_i=d)\\
								& \phantom{=} + \esp{Y_i^{0,0}|T_i=n}\Pr(T_i=n).
\end{align*}

And thus:

\begin{align*}
\esp{Y_i|R_i=1}-\esp{Y_i|R_i=0} & = (\esp{Y_i^{1,1}|T_i=a}-\esp{Y_i^{1,0}|T_i=a})\Pr(T_i=a)\\
                                & \phantom{=}+ (\esp{Y_i^{1,1}|T_i=c}-\esp{Y_i^{0,0}|T_i=c})\Pr(T_i=c) \\
  							                & \phantom{=} - (\esp{Y_i^{1,0}|T_i=d}-\esp{Y_i^{0,1}|T_i=d})\Pr(T_i=d)\\
  							                & \phantom{=} + (\esp{Y_i^{0,1}|T_i=n}-\esp{Y_i^{0,0}|T_i=n})\Pr(T_i=n).
\end{align*}

Using Assumption \@ref(def:ExclRestr), we have:

\begin{align*}
\esp{Y_i|R_i=1}-\esp{Y_i|R_i=0} & = (\esp{Y_i^{1}|T_i=a}-\esp{Y_i^{1}|T_i=a})\Pr(T_i=a)\\
                                & \phantom{=}+ (\esp{Y_i^{1}|T_i=c}-\esp{Y_i^{0}|T_i=c})\Pr(T_i=c) \\
  							                & \phantom{=} - (\esp{Y_i^{1}|T_i=d}-\esp{Y_i^{0}|T_i=d})\Pr(T_i=d)\\
  							                & \phantom{=} + (\esp{Y_i^{0}|T_i=n}-\esp{Y_i^{0}|T_i=n})\Pr(T_i=n)\\
  							                & = \esp{Y_i^{1}-Y_i^{0}|T_i=c}\Pr(T_i=c) \\
  							                & \phantom{=} - \esp{Y_i^{1}-Y_i^{0}|T_i=d}\Pr(T_i=d).
\end{align*}

Under Assumption \@ref(def:Mono), we have:
  
\begin{align*}
\esp{Y_i|R_i=1}-\esp{Y_i|R_i=0} &  = \esp{Y_i^{1}-Y_i^{0}|T_i=c}\Pr(T_i=c)\\
                                 & = \Delta^Y_{LATE}\Pr(T_i=c).
\end{align*}

We also have:

\begin{align*}
\Pr(D_i=1|R_i=1) & = \Pr(D^1_i=1|R_i=1)\\
                & =  \Pr(D^1_i=1\cap (D_i^0=1\cup D_i^0=0) |R_i=1)\\
                & =  \Pr(D^1_i=1\cap D_i^0=1\cup D^1_i=1\cap D_i^0=0 |R_i=1)\\
                & =  \Pr(D^1_i=D_i^0=1\cup D^1_i-D_i^0=0 |R_i=1)\\
                & =  \Pr(T_i=a\cup T_i=c |R_i=1)\\
               & =  \Pr(T_i=a|R_i=1)+\Pr(T_i=c|R_i=1)\\
               & =  \Pr(T_i=a)+\Pr(T_i=c),
\end{align*}

where the first equality follows from Assumption \@ref(def:RandEncouragValid) and the fact that $D_i=R_iD_i^1+(1-R_i)D_i^0$, so that $D_i|R_i=1=D_i^1$.
The second equality follows from the fact that $\left\{ D_i^0=1,D_i^0=0\right\}$ is a partition of the sample space.
The third equality follows from usual rules of logic and the fourth equality from the fact that $D_i^1$ and $D_i^0$ can only take values zero and one.
The fifth equality follows from the definition of $T_i$.
The sixth equaity follows from the rule of addition in probability and the fact that $T_i=a$ and $T_i=c$ are disjoint.
The final equality follows from Lemma \@ref(lem:UnconfTypes).

Using a similar reasoning, we have:

\begin{align*}
\Pr(D_i=1|R_i=0) & = \Pr(T_i=a)+ \Pr(T_i=d).
\end{align*}

As a consequence, under Assumption \@ref(def:Mono), we have:

\begin{align*}
\Pr(D_i=1|R_i=1)-\Pr(D_i=1|R_i=0) & = \Pr(T_i=c).
\end{align*}

Using Assumption \@ref(def:Fstage) proves the result. 

### Proof of Theorem \@ref(thm:WaldIV) {#proofWaldIV}

In matrix notation, we have:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_1 \\	\vdots \\	Y_N \end{array}\right)}_{Y} & =
  \underbrace{\left(\begin{array}{cc}	1 & D_1\\	\vdots & \vdots\\	1 & D_N\end{array}\right)}_{X}
  \underbrace{\left(\begin{array}{c}	\alpha \\	\beta \end{array}\right)}_{\Theta}+
  \underbrace{\left(\begin{array}{c}	U_1 \\	\vdots \\	U_N \end{array}\right)}_{U}
\end{align*}

and

\begin{align*}
  \left(\begin{array}{c}  D_1 \\	\vdots \\	D_N \end{array}\right) & =
  \underbrace{\left(\begin{array}{cc}	1 & R_1\\	\vdots & \vdots\\	1 & R_N\end{array}\right)}_{R}
  \left(\begin{array}{c}	\gamma \\	\tau \end{array}\right)+
  \left(\begin{array}{c}	V_1 \\	\vdots \\	V_N \end{array}\right)
\end{align*}

The IV estimator is:

\begin{align*}
	\hat{\Theta}_{IV} &  = (R'X)^{-1}R'Y
\end{align*}

If there is at least one observation with $R_i=1$ and $D_i=1$, $R'X$ is invertible (its determinant is non null) and we have (ommitting the summation index for simplicity):

\begin{align*}
(R'X)^{-1} &  = \left(\begin{array}{cc} N & \sum D_i \\ \sum R_i & \sum D_iR_i \end{array}\right)^{-1} \\
                & = \frac{1}{N\sum D_iR_i-\sum D_i\sum R_i}\left(\begin{array}{cc} \sum D_iR_i & -\sum D_i \\ -\sum R_i & N \end{array}\right)
\end{align*}

Since:

\begin{align*}
R'Y &  = \left(\begin{array}{c} \sum Y_i \\ \sum Y_iR_i \end{array}\right),
\end{align*}

we have:

\begin{align*}
  \hat{\Theta}_{IV} &  =  \left(
                              \begin{array}{c}
                                \frac{\sum Y_i\sum D_iR_i-\sum D_i\sum Y_iR_i}{N\sum D_iR_i -\sum D_iR_i}\\
                                \frac{N\sum Y_iR_i-\sum R_i\sum Y_i}{N\sum D_iR_i-\sum D_iR_i}
                              \end{array}
                          \right)
\end{align*}

As a consequence, $\hat{\beta}_{IV}$ is equal to the ratio of two OLS estimators ($Y_i$ on $R_i$ and a constant and $D_i$ on the same regressors) (see the proof of Lemma \@ref(lem:WWOLS) in section \@ref(proofCLT), just after "Using $D_i^2=D_i$").
We can use Lemma \@ref(lem:WWOLS) stating that the OLS estimator is the WW estimator to prove the result.

### Proof of Theorem \@ref(thm:asymWald) {#ProofAsymWald}

In order to derive the asymptotic distribution of the Wald estimator, I first use Theorem \@ref(thm:WaldIV) which implies that the asymptotic distribution of Wald is the same as that of $\hat{\beta}_{IV}$.
Now, I'm going to derive the asymptotic distribution of the IV estimator.

```{lemma,asympIV,name='Asymptotic Distribution of the IV Estimator'}
Under Independence and Validity of the Instrument, Exclusion Restriction and Full Rank, we have:

\begin{align*}
  \sqrt{N}(\hat{\Theta}_{IV}-\Theta) &  \stackrel{d}{\rightarrow}
  \mathcal{N}\left(\begin{array}{c}	0\\	0\end{array},
  (\sigma_{RX}^{-1})'\mathbf{V_{ru}}\sigma_{RX}^{-1}\right), 
\end{align*}

with 
\begin{align*}
\sigma_{RX}^{-1}& = \frac{\left(\begin{array}{cc}	\esp{D_iR_i} & -\Pr(D_i=1)\\
                                          -\Pr(R_i=1) & 1 
                          \end{array}\right)}{(\Pr(D_i=1|R_i=1)-\Pr(D_i=1|R_i=0))\Pr(R_i=1)(1-\Pr(R_i=1))}
                          \\
\mathbf{V_{ru}}&= \esp{U_i^2\left(\begin{array}{cc}  1 & R_i\\  R_i & R_i\end{array}\right)}                                                                
\end{align*}
```

```{proof}
\begin{align*}
\sqrt{N}(\hat{\Theta}_{IV}-\Theta) & = \sqrt{N}((R'X)^{-1}R'Y-\Theta) \\
                                    & = \sqrt{N}((R'X)^{-1}R'(X\Theta+U)-\Theta) \\
                                    & = \sqrt{N}((R'X)^{-1}R'X\Theta+(X'X)^{-1}X'U)-\Theta) \\
                                    & = \sqrt{N}(R'X)^{-1}R'U \\
                                    & = N(R'X)^{-1}\frac{\sqrt{N}}{N}R'U
\end{align*}

Using Slutsky's Theorem, we have:

\begin{align*}
\sqrt{N}(\hat{\Theta}_{IV}-\Theta) & \stackrel{d}{\rightarrow} \sigma_{RX}^{-1}ru,
\end{align*}

where $\sigma_{RX}^{-1}$ is a matrix of constants and $ru$ is a random variable.

We know that $\plims N(R'X)^{-1}=\sigma_{RX}^{-1}$.
So:

\begin{align*}
N(R'X)^{-1} & = \frac{N}{N\sum D_iR_i-\sum D_i\sum R_i}\left(\begin{array}{cc} \sum D_iR_i & -\sum D_i \\ -\sum R_i & N \end{array}\right) \\
            & = \frac{1}{\frac{\sum D_iR_i}{N}-\frac{\sum D_i}{N}\frac{\sum R_i}{N}} 
                  \left(\begin{array}{cc} 
                          \frac{\sum D_iR_i}{N} & -\frac{\sum D_i}{N} \\ -\frac{\sum R_i}{N} & 1 
                        \end{array}
                  \right) 
\end{align*}

$\frac{\sum D_iR_i}{N}-\frac{\sum D_i}{N}\frac{\sum R_i}{N}$ is equal to the numerator of the OLS coefficient of a regression of $D_i$ on $R_i$ and a constant (Proof of Lemma 3 in Lecture 0).
As a consequence of Lemma 3 in Lecture 0, it can be written as the With/Without estimator multiplied by the denominator of the OLS estimator, which is simply the variance of $R_i$.

Let's turn to $\frac{\sqrt{N}}{N}R'U\stackrel{d}{\rightarrow}xu$:

\begin{align*}
\frac{\sqrt{N}}{N}R'U & = \sqrt{N}\left(\begin{array}{c}  \frac{1}{N}\sum^{i=1}_{N}U_i\\  \frac{1}{N}\sum^{i=1}_{N}R_iU_i\end{array}\right)
\end{align*}

We know that, under Validity of Randomization, both random variables have mean zero: 

\begin{align*}
\esp{U_i}& = \esp{U_i|R_i=1}\Pr(R_i=1)+\esp{U_i|R_i=0}\Pr(R_i=0)=0 \\
\esp{U_iR_i}& = \esp{U_i|R_i=1}\Pr(R_i=1)=0
\end{align*}

Their covariance matrix $\mathbf{V_{ru}}$ can be computed as follows:

\begin{align*}
\mathbf{V_{ru}} & = \esp{\left(\begin{array}{c}  U_i\\	UiR_i\end{array}\right)\left(\begin{array}{cc}	U_i&	UiR_i\end{array}\right)}
                  - \esp{\left(\begin{array}{c}	U_i\\	UiR_i\end{array}\right)}\esp{\left(\begin{array}{cc}	U_i&	UiR_i\end{array}\right)}\\
                & = \esp{\left(\begin{array}{cc}	U_i^2 & U_i^2R_i\\	Ui^2R_i & U_i^2R_i^2\end{array}\right)} 
                  = \esp{U_i^2\left(\begin{array}{cc}	1 & R_i\\	R_i & R_i^2\end{array}\right)} 
                  = \esp{U_i^2\left(\begin{array}{cc}	1 & R_i\\	R_i & R_i\end{array}\right)} 
\end{align*}

Using the Vector CLT, we have that $\frac{\sqrt{N}}{N}R'U\stackrel{d}{\rightarrow}\mathcal{N}\left(\begin{array}{c}  0\\	0\end{array},\mathbf{V_{ru}}\right)$.
Using Slutsky's theorem and the LLN gives the result.
```

From Lemma \@ref(lem:asympIV), we know that $\sqrt{N}(\hat{\beta}_{IV}-\beta)\stackrel{d}{\rightarrow}\mathcal{N}(0,\sigma^2_{\beta})$, where $\sigma^2_{\beta}$ is the lower diagonal term of $(\sigma_{RX}^{-1})'\mathbf{V_{ru}}\sigma_{RX}^{-1}$.
Using the convention $p^R=\Pr(R_i=1)$, $p^D=\Pr(D_i=1)$, $p^D_1=\Pr(D_i=1|R_i=1)$, $p^D_0=\Pr(D_i=1|R_i=0)$ and $p^{DR}=\esp{D_iR_i}$, we have:

\begin{align*}
(&\sigma_{RX}^{-1})'\mathbf{V_{ru}}\sigma_{RX}^{-1} \\
                   & = \frac{1}{((p^D_1-p^D_0)p^R(1-p^R))^2}
                  \left(\begin{array}{cc}
                         p^{DR}  & -p^R\\
                        -p^D & 1
                          \end{array}\right)
                          \esp{U_i^2\left(\begin{array}{cc}  1 & R_i\\  R_i & R_i\end{array}\right)}
                        \left(\begin{array}{cc}
                                         p^{DR}  & -p^D\\
                                          -p^R & 1
                          \end{array}\right)\\
                    & = \frac{1}{((p^D_1-p^D_0)p^R(1-p^R))^2}
                         \left(\begin{array}{cc}
                         p^{DR}\esp{U_i^2}-p^R\esp{U_i^2R_i} & \esp{U_i^2R_i}(p^{DR}-p^R)\\
                        \esp{U_i^2R_i}-p^D\esp{U_i^2} & \esp{U_i^2R_i}(1-p^D)
                          \end{array}\right)
                          \left(\begin{array}{cc}
                                         p^{DR}  & -p^D\\
                                          -p^R & 1
                          \end{array}\right)\\
                    & = \frac{\left(\begin{array}{cc}
                          p^{DR}(p^{DR}\esp{U_i^2}-p^R\esp{U_i^2R_i})- p^R\esp{U_i^2R_i}(p^{DR}-p^R)
                            & \esp{U_i^2R_i}(p^{DR}-p^R)-p^{D}(p^{DR}\esp{U_i^2}-p^R\esp{U_i^2R_i})\\
                          p^{DR}(\esp{U_i^2R_i}-p^D\esp{U_i^2})-p^R\esp{U_i^2R_i}(1-p^D)
                            & \esp{U_i^2R_i}(1-p^D) - p^{D}(\esp{U_i^2R_i}-p^D\esp{U_i^2})
                          \end{array}\right)}{((p^D_1-p^D_0)p^R(1-p^R))^2}
 \end{align*}

As a consequence:

\begin{align*}
\sigma^2_{\beta} & = \frac{\esp{U_i^2R_i}(1-p^D) - p^{D}(\esp{U_i^2R_i}-p^D\esp{U_i^2})}{((p^D_1-p^D_0)p^R(1-p^R))^2} \\
                  & = \frac{(p^D)^2\esp{U_i^2}+(1-2p^D)\esp{U_i^2R_i}}{((p^D_1-p^D_0)p^R(1-p^R))^2}\\
                  & = \frac{(p^D)^2(\esp{U_i^2|R_i=1}p^R+\esp{U_i^2|R_i=0}(1-p^R))+(1-2p^D)\esp{U_i^2|R_i=1}p^R}{((p^D_1-p^D_0)p^R(1-p^R))^2}\\
                  & = \frac{(p^D)^2\esp{U_i^2|R_i=0}(1-p^R)+(1-2p^D+(p^D)^2)\esp{U_i^2|R_i=1}p^R}{((p^D_1-p^D_0)p^R(1-p^R))^2}\\
                  & = \frac{(p^D)^2\esp{U_i^2|R_i=0}(1-p^R)+(1-p^D)^2\esp{U_i^2|R_i=1}p^R}{((p^D_1-p^D_0)p^R(1-p^R))^2}\\
                  & = \frac{1}{(p^D_1-p^D_0)^2}\left[\left(\frac{p^D}{p^R}\right)^2\frac{\esp{U_i^2|R_i=0}}{1-p^R}+\left(\frac{1-p^D}{1-p^R}\right)^2\frac{\esp{U_i^2|R_i=1}}{p^R}\right].
\end{align*}

Note that, under monotonicity, $p^C=p^D_1-p^D_0$ and:

\begin{align*}
\esp{U_i^2|R_i=1} & = p^{AT}\var{Y_i^1|T_i=AT}+p^C\var{Y_i^1|T_i=C}+p^{NT}\var{Y_i^0|T_i=NT} \\
\esp{U_i^2|R_i=0}  & = p^{AT}\var{Y_i^1|T_i=AT}+p^C\var{Y_i^0|T_i=C}+p^{NT}\var{Y_i^0|T_i=NT}.
 \end{align*}

The final result comes from the fact that:

\begin{align*}
\frac{1}{(p^C)^2} &  \left[\left(\frac{p^D}{p^R}\right)^2\frac{1}{1-p^R}+\left(\frac{1-p^D}{1-p^R}\right)^2\frac{1}{p^R}\right]\\
  & = \frac{(p^D)^2(1-p^R)+(1-p^D)^2p^R}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^D)^2-(p^D)^2p^R+p^R-2p^Dp^R+(p^D)^2p^R}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^D)^2+p^R-2p^Dp^R}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^D-p^R)^2+p^R-(p^R)^2}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^D-p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^{AT}+p^Cp^R-p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^{AT}+(1-p^{AT}-p^{NT})p^R-p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^{AT}+(1-p^{AT}-p^{NT})p^R-p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^{AT}+p^R-p^{AT}p^R-p^{NT}p^R-p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2} \\
  & = \frac{(p^{AT}(1-p^R)-p^{NT}p^R)^2+p^R(1-p^R)}{(p^Cp^R(1-p^R))^2},
\end{align*}

where the seventh equality uses the fact that $p^C+p^{AT}+p^{NT}=1$.

## Proofs of results in Chapter \@ref(NE)

### Proof of Theorem \@ref(thm:EstimDID) {#proofEstimDID}

Let us start with the proof that $\hat{\beta}^{FD}=\hat{\Delta}^Y_{DID}$. 
Using Lemma \@ref(lem:WWOLS), we have that $\hat{\beta}^{FD}=\hat{\Delta}^{Y_A-Y_B}_{WW}$.
From there, since $\sum_{i=1}^N(Y_{i,A}-Y_{i,B})D_i= \sum_{i=1}^NY_{i,A}D_i- \sum_{i=1}^NY_{i,B}D_i$, we have $\hat{\beta}^{FD}=\hat{\Delta}^Y_{DID}$.

In order to prove the result for the OLS DID estimator, it is convenient to write the model in matrix form (where we rank all the observations from the first period in the first lines of each matrix and vector):

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_{1,B} \\	\vdots \\	Y_{N,B} \\Y_{1,A} \\	\vdots \\	Y_{N,A} \end{array}\right)}_{Y} & =
    \underbrace{\left(\begin{array}{cccc}	1 & D_1 & T_{1,B} & D_1T_{1,B}\\	\vdots & \vdots & \vdots & \vdots\\	1 & D_N & T_{N,B} & D_NT_{N,B} \\
                                        1 & D_1 & T_{1,A} & D_1T_{1,A}\\	\vdots & \vdots & \vdots & \vdots\\	1 & D_N & T_{N,A} & D_NT_{N,A}\end{array}\right)}_{X}
  \underbrace{\left(\begin{array}{c}	\alpha \\ \mu \\ \delta \\	\beta \end{array}\right)}_{\Theta} +
  \underbrace{\left(\begin{array}{c}	\epsilon_{1,B} \\	\vdots \\	\epsilon_{N,B} \\ \epsilon_{1,A} \\	\vdots \\	\epsilon_{N,A} \end{array}\right)}_{\epsilon}
\end{align*}

Now, using the fact that $T_{i,B}=0$ and $T_{i,A}=1$, $\forall i$, we can write matrix $X$ as follows:

\begin{align*}
  X & = \left(\begin{array}{cccc}	1 & D_1 & 0 & 0\\	\vdots & \vdots & \vdots & \vdots\\	1 & D_N & 0 & 0 \\
                                        1 & D_1 & 1 & D_1\\	\vdots & \vdots & \vdots & \vdots\\	1 & D_N & 1 & D_N\end{array}\right)
\end{align*}

Doing some matrix multiplication and factoring $N$, we have:

\begin{align*}
  X'X & = N\underbrace{\left(\begin{array}{cccc}
                    2 & 2\bar{D} & 1 & \bar{D}\\
                    2\bar{D} & 2\bar{D} & \bar{D} & \bar{D} \\
                    1 & \bar{D} & 1 & \bar{D}\\
                    \bar{D} & \bar{D} & \bar{D} & \bar{D}
            \end{array}\right)}_{x'x}
\end{align*}

with $\bar{D}=\frac{1}{N}\sum_{i=1}^ND_i$, and using the fact that $D_i^2=D_i$ since $D_i\in\left\{0,1\right\}$.
Using results on the inverse of a 4 by 4 matrix presented [here](https://semath.info/src/inverse-cofactor-ex4.html) and collecting terms patiently, we find that the determinant of $xx$ is equal to:

\begin{align*}
  \det(x'x) & = \bar{D}^2(1-\bar{D})^2
\end{align*}

and its adjugate is equal to:

\begin{align*}
  \tilde{x'x} & = \bar{D}(1-\bar{D})
                  \left(\begin{array}{cccc}
                    \bar{D} & -\bar{D} & -\bar{D} & \bar{D}\\
                    -\bar{D} & 1 & \bar{D} & -1 \\
                    -\bar{D} & \bar{D} & 2\bar{D} & -2\bar{D}\\
                    \bar{D} & -1 & -2\bar{D} & 2
            \end{array}\right)
\end{align*}

We also have that:

\begin{align*}
  X'Y & = N\left(\begin{array}{c}
              \bar{Y}_B+\bar{Y}_A \\
              \bar{D}(\bar{Y}^1_B+\bar{Y}^1_A)\\
              \bar{Y}_A \\
              \bar{D}\bar{Y}^1_A
            \end{array}\right)
\end{align*}

with $\bar{Y}_t=\frac{1}{N}\sum_{i=1}^NY_{i,t}$ and $\bar{Y}^1_t=\frac{1}{\sum_{i=1}^ND_i}\sum_{i=1}^ND_iY_{i,t}$ and $\bar{Y}^0_t=\frac{1}{\sum_{i=1}^N(1-D_i)}\sum_{i=1}^N(1-D_i)Y_{i,t}$ and using the fact that $\sum_{i=1}^ND_iY_{i,t}=N\bar{D}\bar{Y}^1_t$.
Using the fact that $Y_{i,t}=D_iY_{i,t}+(1-D_i)Y_{i,t}$, we have:

\begin{align*}
  \bar{Y}_t & = \frac{\sum_{i=1}^ND_i}{N}\frac{\sum_{i=1}^ND_iY_{i,t}}{\sum_{i=1}^ND_i}+\frac{\sum_{i=1}^N(1-D_i)}{N}\frac{\sum_{i=1}^N(1-D_i)Y_{i,t}}{\sum_{i=1}^N(1-D_i)} \\
            & = \bar{D}\bar{Y}^1_t+(1-\bar{D})\bar{Y}^0_t.
 \end{align*}

We thus have:

\begin{align*}
  X'Y & = N\left(\begin{array}{c}
              \underbrace{\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}(\bar{Y}^1_B-\bar{Y}^0_B+\bar{Y}^1_A-\bar{Y}^0_A)}_{\mathbf{A}} \\
              \underbrace{\bar{D}(\bar{Y}^1_B+\bar{Y}^1_A)}_{\mathbf{B}}\\
              \underbrace{\bar{Y}^0_A+\bar{D}(\bar{Y}^1_A-\bar{Y}^0_A)}_{\mathbf{C}} \\
              \underbrace{\bar{D}\bar{Y}^1_A}_{\mathbf{D}}
            \end{array}\right)
\end{align*}

Using the fact that $(X'X)^{-1}=(Nx'x)^{-1}=\frac{1}{N}(x'x)^{-1}=\frac{1}{N}\frac{\tilde{x'x}}{\det(x'x)}$, we have:

\begin{align*}
  \hat{\Theta}^{OLS} & = (X'X)^{-1}X'Y \\
         & = \frac{1}{\bar{D}(1-\bar{D})}
            \left(\begin{array}{c}
              \bar{D}(\mathbf{A}-\mathbf{B}-\mathbf{C}+\mathbf{D}) \\
              -\bar{D}\mathbf{A}+\mathbf{B}+\bar{D}\mathbf{C}-\mathbf{D} \\
              \bar{D}(-\mathbf{A}+\mathbf{B}+2\mathbf{C}-2\mathbf{D})\\
              \bar{D}\mathbf{A}-\mathbf{B}-2\bar{D}\mathbf{C}+2\mathbf{D}
            \end{array}\right)
\end{align*}

Let's take each term in turn:

\begin{align*}
  \hat{\alpha}^{OLS} & = \frac{1}{1-\bar{D}}
            \left(\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}(\bar{Y}^1_B-\bar{Y}^0_B+\bar{Y}^1_A-\bar{Y}^0_A)
            -\bar{D}(\bar{Y}^1_B+\bar{Y}^1_A)
            -(\bar{Y}^0_A+\bar{D}(\bar{Y}^1_A-\bar{Y}^0_A))
            +\bar{D}\bar{Y}^1_A\right)\\
        & = \frac{1}{1-\bar{D}}
              \left(\bar{Y}^0_B(1-\bar{D})
                    +\bar{Y}^0_A(1-\bar{D}-1+\bar{D})
                    +\bar{Y}^1_B(\bar{D}-\bar{D})
                    +\bar{Y}^1_A(\bar{D}-\bar{D}-\bar{D}+\bar{D})\right)\\
        & = \bar{Y}^0_B
\end{align*}

\begin{align*}
  \hat{\mu}^{OLS} & = \frac{1}{\bar{D}(1-\bar{D})}\left(
            -\bar{D}(\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}(\bar{Y}^1_B-\bar{Y}^0_B+\bar{Y}^1_A-\bar{Y}^0_A))
            +\bar{D}(\bar{Y}^1_B+\bar{Y}^1_A)
            +\bar{D}(\bar{Y}^0_A+\bar{D}(\bar{Y}^1_A-\bar{Y}^0_A))
            -\bar{D}\bar{Y}^1_A\right)\\
      & =  \frac{1}{1-\bar{D}}\left(
            -\bar{Y}^0_B(1-\bar{D})
            +\bar{Y}^0_A(-1+\bar{D}+1-\bar{D})
            +\bar{Y}^1_B(1-\bar{D})
            +\bar{Y}^1_A(-\bar{D}+1+\bar{D}-1)\right) \\
      & = \bar{Y}^1_B-\bar{Y}^0_B
 \end{align*}


\begin{align*}
  \hat{\delta}^{OLS} & =\frac{1}{1-\bar{D}}\left(
            -(\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}(\bar{Y}^1_B-\bar{Y}^0_B+\bar{Y}^1_A-\bar{Y}^0_A))
            +(\bar{Y}^1_B+\bar{Y}^1_A)
            +2(\bar{Y}^0_A+\bar{D}(\bar{Y}^1_A-\bar{Y}^0_A))
            -2\bar{D}\bar{Y}^1_A\right)\\
      & =  \frac{1}{1-\bar{D}}\left(
            -\bar{Y}^0_B(1-\bar{D})
            +\bar{Y}^0_A(2(1-\bar{D})-(1-\bar{D}))
            +\bar{Y}^1_B(\bar{D}-\bar{D})
            +\bar{Y}^1_A(\bar{D}-\bar{D}+2\bar{D}-2\bar{D})\right) \\
      & = \bar{Y}^0_A-\bar{Y}^0_B
 \end{align*}

\begin{align*}
  \hat{\beta}^{OLS} & =\frac{1}{\bar{D}(1-\bar{D})}\left(
            \bar{D}(\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}(\bar{Y}^1_B-\bar{Y}^0_B+\bar{Y}^1_A-\bar{Y}^0_A))
            -\bar{D}(\bar{Y}^1_B+\bar{Y}^1_A)
            -2 \bar{D}(\bar{Y}^0_A+\bar{D}(\bar{Y}^1_A-\bar{Y}^0_A))
            +2\bar{D}\bar{Y}^1_A\right)\\
      & =  \frac{1}{1-\bar{D}}\left(
            \bar{Y}^0_B(1-\bar{D})
            +\bar{Y}^0_A((1-\bar{D})-2(1-\bar{D}))
            +\bar{Y}^1_B(\bar{D}-1)
            +\bar{Y}^1_A(\bar{D}-1-2\bar{D}+2)\right) \\
      & = \bar{Y}^1_A-\bar{Y}^1_B-(\bar{Y}^0_A-\bar{Y}^0_B)
 \end{align*}

This last results proves that $\hat{\beta}^{OLS}=\hat{\Delta}^Y_{DID}$.

For the within estimator, it can be written in matrix form as follows:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_{1,B}-\bar{Y}_1 \\	\vdots \\	Y_{N,B}-\bar{Y}_N \\Y_{1,A}-\bar{Y}_1 \\	\vdots \\	Y_{N,A}-\bar{Y}_N \end{array}\right)}_{Y^W} & =
    \underbrace{\left(\begin{array}{ccc}	1  & 0 & -\bar{D}_1\\	\vdots & \vdots & \vdots \\	1 & 0 & -\bar{D}_N \\
                                        1 & 1 & D_1-\bar{D}_1\\	\vdots & \vdots & \vdots \\	1 & 1 & D_N-\bar{D}_N\end{array}\right)}_{X^W}
  \underbrace{\left(\begin{array}{c}	\alpha^W \\ \delta^W \\	\beta^W \end{array}\right)}_{\Theta^{W}} +
  \underbrace{\left(\begin{array}{c}	\epsilon^W_{1,B} \\	\vdots \\	\epsilon^W_{N,B} \\ \epsilon^W_{1,A} \\	\vdots \\	\epsilon^W_{N,A} \end{array}\right)}_{\epsilon^W}
\end{align*}

We have:

\begin{align*}
  {X^W}'X^W & = N\underbrace{\left(\begin{array}{ccc}
                    2 &  1 & 0\\
                    1 & 1  & \frac{\bar{D}}{2} \\
                    0 & \frac{\bar{D}}{2} & \frac{\bar{D}}{2}
            \end{array}\right)}_{{x^W}'x^W}
\end{align*}

This is because:

\begin{align*}
  {X^W}'X^W & = \left(\begin{array}{ccc}
                    2N & N & -\sum_{i=1}^N\bar{D}_i+\sum_{i=1}^N(D_i-\bar{D}_i)\\
                    N & N  & \sum_{i=1}^N(D_i-\bar{D}_i) \\
                    -\sum_{i=1}^N\bar{D}_i+\sum_{i=1}^N(D_i-\bar{D}_i) & \sum_{i=1}^N(D_i-\bar{D}_i) & \sum_{i=1}^N\bar{D}_i^2+\sum_{i=1}^N(D_i-\bar{D}_i)^2
            \end{array}\right)
\end{align*}

and:

\begin{align*}
  \sum_{i=1}^N\bar{D}_i & = \frac{1}{2}\sum_{i=1}^N(D_{i,B}+D_{i,A}) \\
                        & = \frac{1}{2}\sum_{i=1}^ND_{i} \\
                        & = \frac{1}{2}N\bar{D}\\
  \sum_{i=1}^N(D_i-\bar{D}_i) & = N\bar{D}-\frac{1}{2}N\bar{D} \\
                            & = \frac{1}{2}N\bar{D}\\
  \sum_{i=1}^N\bar{D}^2_i & = \frac{1}{4}\sum_{i=1}^N(D_{i,B}+D_{i,A})^2\\
                          & = \frac{1}{4}\sum_{i=1}^ND^2_{i} \\
                          & = \frac{1}{4}N\bar{D} \\
  \sum_{i=1}^N(D_i-\bar{D}_i)^2 & = \sum_{i=1}^N(D_{i}-\frac{1}{2}D_{i})^2\\
                                & = \frac{1}{4}N\bar{D}
\end{align*}

Now we can use the results [here](https://study.com/academy/lesson/finding-the-inverse-of-a-3x3-matrix.html) and [here](https://metric.ma.ic.ac.uk/metric_public/matrices/inverses/inverses2.html) to compute the inverse of the ${x^W}'x^W$ matrix.
Let us first compute the determinant:

\begin{align*}
  \det({x^W}'x^W) & = 2(\frac{\bar{D}}{2}-\frac{\bar{D}^2}{4}) - \frac{\bar{D}}{2}\\
                  & = \frac{1}{2}\bar{D}(1-\bar{D}).
\end{align*}

And then the adjugate:

\begin{align*}
  \tilde{{x^W}'x^W} & = \left(\begin{array}{ccc}
                    \frac{\bar{D}}{2}(1-\frac{\bar{D}}{2}) & -\frac{\bar{D}}{2} & \frac{\bar{D}}{2}\\
                    -\frac{\bar{D}}{2} & \bar{D}  & -\bar{D}\\
                    \frac{\bar{D}}{2} & -\bar{D} & 1
            \end{array}\right)
\end{align*}

Let us now examine ${X^W}'Y^W$:

\begin{align*}
  {X^W}'Y^W & = \left(\begin{array}{c}
                \sum_{i=1}^N(Y_{i,B}-\bar{Y}_i)+\sum_{i=1}^N(Y_{i,A}-\bar{Y}_i)\\
                \sum_{i=1}^N(Y_{i,A}-\bar{Y}_i) \\
                -\sum_{i=1}^N\bar{D}_i(Y_{i,B}-\bar{Y}_i)+\sum_{i=1}^N(D_i-\bar{D}_i)(Y_{i,A}-\bar{Y}_i)
            \end{array}\right)
\end{align*}

We have:

\begin{align*}
  \sum_{i=1}^N(Y_{i,B}-\bar{Y}_i) & = N\bar{Y}_B-\frac{1}{2}N(\bar{Y}_B+\bar{Y}_A)\\
                                  & = \frac{1}{2}N(\bar{Y}_B-\bar{Y}_A)\\
  \sum_{i=1}^N(Y_{i,A}-\bar{Y}_i) & = \frac{1}{2}N(\bar{Y}_A-\bar{Y}_B)\\
  \sum_{i=1}^N\bar{D}_i(Y_{i,B}-\bar{Y}_i) & = \sum_{i=1}^N\frac{1}{2}D_i(Y_{i,B}-\frac{1}{2}\sum_{i=1}^N(Y_{i,B}+Y_{i,A}))\\
                                    & = \sum_{i=1}^N\frac{1}{2}D_i\frac{1}{2}(Y_{i,B}-Y_{i,A})\\
                                    & = \frac{1}{4}\sum_{i=1}^ND_i(Y_{i,B}-Y_{i,A})\\
                                    & = \frac{1}{4}N\bar{D}(\bar{Y}^1_B-\bar{Y}^1_A)\\
  \sum_{i=1}^N(D_i-\bar{D}_i)(Y_{i,A}-\bar{Y}_i) & = \sum_{i=1}^N(D_i-\frac{1}{2}D_i)(Y_{i,A}-\frac{1}{2}\sum_{i=1}^N(Y_{i,B}+Y_{i,A}))\\
                                                & = \frac{1}{4}\sum_{i=1}^ND_i(Y_{i,A}-Y_{i,B})\\
                                                & = \frac{1}{4}N\bar{D}(\bar{Y}^1_A-\bar{Y}^1_B).
\end{align*}

So, we have:

\begin{align*}
  ({X^W}'X^W)^{-1}{X^W}'Y^W  & = \frac{2}{N\bar{D}(1-\bar{D})}
            \left(\begin{array}{ccc}
                    \frac{\bar{D}}{2}(1-\frac{\bar{D}}{2}) & -\frac{\bar{D}}{2} & \frac{\bar{D}}{2}\\
                    -\frac{\bar{D}}{2} & \bar{D}  & -\bar{D}\\
                    \frac{\bar{D}}{2} & -\bar{D} & 1
            \end{array}\right)
            \left(\begin{array}{c}
                0\\
                \frac{N}{2}(\bar{Y}_A-\bar{Y}_B)\\
                \frac{N}{2}\bar{D}(\bar{Y}^1_A-\bar{Y}^1_B)
            \end{array}\right)
\end{align*}

We thus have:

\begin{align*}
  \hat{\beta}^W & = \frac{2}{N\bar{D}(1-\bar{D})}\left(-\bar{D}\frac{N}{2}(\bar{Y}_A-\bar{Y}_B)+\frac{N}{2}\bar{D}(\bar{Y}^1_A-\bar{Y}^1_B)\right)\\
                & = \frac{1}{1-\bar{D}}\left(\bar{Y}^1_A-\bar{Y}^1_B-(\bar{Y}_A-\bar{Y}_B)\right)\\
\end{align*}

Using the fact that $\bar{Y}_t=\bar{D}\bar{Y}_t^1+(1-\bar{D})\bar{Y}^0_t$, we have $\bar{Y}_A-\bar{Y}_B=(1-\bar{D})(\bar{Y}^0_A-\bar{Y}^0_B)+\bar{D}(\bar{Y}_A^1-\bar{Y}_B^1)$.

As a consequence:

\begin{align*}
  \hat{\beta}^W & = \frac{1-\bar{D}}{1-\bar{D}}\left(\bar{Y}^1_A-\bar{Y}^1_B-(\bar{Y}^0_A-\bar{Y}^0_B)\right)\\
                & =  \bar{Y}^1_A-\bar{Y}^1_B-(\bar{Y}^0_A-\bar{Y}^0_B),
\end{align*}

which proves that $\hat{\beta}^{W}=\hat{\Delta}^Y_{DID}$.

Now for $\hat{\beta}^{LSDV}$, the estimator can be written in matrix form as follows:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_{1,B} \\	\vdots \\	Y_{N,B} \\Y_{1,A} \\	\vdots \\	Y_{N,A} \end{array}\right)}_{Y} & =
    \underbrace{\left(\begin{array}{ccccccc}
    1 & 0 & \dots & 0 & 1 & 0 & D_{1,B}\\
    0 & 1 & \dots & 0 & 1 & 0 & D_{2,B}\\
    \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots  \\
    0 & 0 & \dots & 1 & 1 & 0 & D_{N,B}\\
    1 & 0 & \dots & 0 & 0 & 1 & D_{1,A}\\
    0 & 1 & \dots & 0 & 0 & 1 & D_{2,A}\\
    \vdots & \vdots & \ddots & \vdots & \vdots & \vdots & \vdots  \\
    0 & 0 & \dots & 1 & 0 & 1 & D_{N,A}\\
    \end{array}\right)}_{X^{LSDV}}
  \underbrace{\left(\begin{array}{c}  \mu^{LSDV}_1\\ \vdots \\ \mu^{LSDV}_N \\ \delta^{LSDV}_B \\ \delta^{LSDV}_A \\	\beta^{LSDV} \end{array}\right)}_{\Theta^{LSDV}} +
  \underbrace{\left(\begin{array}{c}	\epsilon^{LSDV}_{1,B} \\	\vdots \\	\epsilon^{LSDV}_{N,B} \\ \epsilon^{LSDV}_{1,A} \\	\vdots \\	\epsilon^{LSDV}_{N,A} \end{array}\right).}_{\epsilon^{LSDV}}
\end{align*}

In order to prove the result, it is going to be very convenient to use [Frish-Waugh-Lovell Theorem](https://bookdown.org/ts_robinson1994/10_fundamental_theorems_for_econometrics/frisch.html).
It can be stated as follows:

```{theorem,FWL,name="Frish-Waugh-Lovell"}
The coefficients on a set of variables $X_2$ estimated by OLS in a linear regression with another set of control variables $X_1$ is equal to the coefficients on the same set of variables estimated by OLS in a linear model where the outcome variable is the residual of regressing $Y$ on $X_1$ by OLS and the explanatory variables are the residuals of regressing $X_2$ on $X_1$. More formally: $\hat{\beta}_2^{OLS}=\hat{\beta}_2^{OLS(MX_1)}$ where:
\begin{align*}
  Y & = X_1\beta_1 + X_2\beta_2 + \epsilon \\
  M_1Y & = M_1X_2\beta_2 + \epsilon^* \\
  M_1 & = I - X_1(X_1'X_1)^{-1}X_1'.
\end{align*}
```

```{proof}
See Section 8.2.2 [here](https://bookdown.org/ts_robinson1994/10_fundamental_theorems_for_econometrics/frisch.html).
```

$M_1$ is called the **prediction** or the **residualizing** matrix.

In our case, let us call $X^{LSDV}_{\mu}$ the first $N$ columns of $X^{LSDV}$.
$X^{LSDV}_{\mu}$ is going to play the role of $X_1$ in Theorem \@ref(thm:FWL).
Let us call $X^{LSDV}_{\delta,D}$ the matrix made of the last three columns of $X^{LSDV}$.
$X^{LSDV}_{\delta,D}$ is going to play the role of $X_2$ in Theorem \@ref(thm:FWL).

Let us first note that ${X^{LSDV}_{\mu}}'X^{LSDV}_{\mu}=2I_{N}$, where $I_{N}$ is the identity matrix of dimension $N$.
As a consequence, $({X^{LSDV}_{\mu}}'X^{LSDV}_{\mu})^{-1}=\frac{1}{2}I_N$.
Now, let us compute ${X^{LSDV}_{\mu}}'Y$:

\begin{align*}
 {X^{LSDV}_{\mu}}'Y  & = \left(\begin{array}{c}
                            Y_{1,B}+Y_{1,A} \\
                            \vdots \\
                            Y_{N,B}+Y_{N,A}
                          \end{array}\right).
\end{align*}

As a consequence, we have:

\begin{align*}
 M^{LSDV}_{\mu}Y  & = Y - X^{LSDV}_{\mu}({X^{LSDV}_{\mu}}'X^{LSDV}_{\mu})^{-1}{X^{LSDV}_{\mu}}'Y \\
                  & = Y-\frac{1}{2} X^{LSDV}_{\mu}I_N
                  \left(\begin{array}{c}
                            Y_{1,B}+Y_{1,A} \\
                            \vdots \\
                            Y_{N,B}+Y_{N,A}
                          \end{array}\right) \\
                  & = \left(\begin{array}{c}
                           Y_{1,B} - \frac{1}{2}(Y_{1,B}+Y_{1,A}) \\
                            \vdots \\
                            Y_{N,B} - \frac{1}{2}(Y_{N,B}+Y_{N,A})\\
                           Y_{1,A} - \frac{1}{2}(Y_{1,B}+Y_{1,A}) \\
                            \vdots \\
                            Y_{N,A} - \frac{1}{2}(Y_{N,B}+Y_{N,A})
                          \end{array}\right).
\end{align*}

And finally:

\begin{align*}
 M^{LSDV}_{\mu}X^{LSDV}_{\delta,D}  & = X^{LSDV}_{\delta,D} - X^{LSDV}_{\mu}({X^{LSDV}_{\mu}}'X^{LSDV}_{\mu})^{-1}{X^{LSDV}_{\mu}}'X^{LSDV}_{\delta,D} \\
                  & = \left(\begin{array}{ccc}
                          \frac{1}{2} & -\frac{1}{2} &  D_{1,B}-\frac{1}{2}(D_{1,B}+D_{1,A}) \\
                          \vdots & \vdots &  \vdots \\
                          \frac{1}{2} & -\frac{1}{2} &  D_{N,B}-\frac{1}{2}(D_{1,B}+D_{1,A}) \\
                          -\frac{1}{2} & \frac{1}{2} &  D_{1,A}-\frac{1}{2}(D_{1,B}+D_{1,A}) \\
                          \vdots & \vdots &  \vdots \\
                          -\frac{1}{2} & \frac{1}{2} &  D_{N,A}-\frac{1}{2}(D_{1,B}+D_{1,A}) \\
                          \end{array}\right).
\end{align*}

Using Theorem \@ref(thm:FWL), we can rewrite the LSDV version of the TWFE model as follows:

\begin{align*}
  	 M^{LSDV}_{\mu}Y & =  M^{LSDV}_{\mu}X^{LSDV}_{\delta,D}
  	                        \left(\begin{array}{c}
  	                        \delta^{LSDV}_B \\ \delta^{LSDV}_A \\	\beta^{LSDV}
  	                        \end{array}\right) + M^{LSDV}_{\mu}\epsilon^{LSDV}
\end{align*}

In a more compact notation, we have, $\forall i\in\left[1,N\right]$ and $\forall t\in\left\{B,A\right\}$:

\begin{align*}
  	Y_{i,t} - \bar{Y}_i  &  = \frac{1}{2}(\delta^{LSDV}_A-\delta^{LSDV}_B)(\uns{t=A}-\uns{t=B}) + \beta^{LSDV}(D_{i,t}-\bar{D}_{i}) + \epsilon^{LSDV}_{i,t}-\bar{\epsilon}^{LSDV}_{i},
\end{align*}

which we can rewrite, for simplicity, as:

\begin{align*}
  	Y_{i,t} - \bar{Y}_i  &  = \tilde{\delta}^{LSDV}_t + \beta^{LSDV}(D_{i,t}-\bar{D}_{i}) + \epsilon^{LSDV}_{i,t}-\bar{\epsilon}^{LSDV}_{i},
\end{align*}

with $\tilde{\delta}^{LSDV}_A=-\tilde{\delta}_B^{LSDV}=\bar{\delta}^{LSDV}$ and $\bar{\delta}^{LSDV}=\frac{1}{2}(\delta^{LSDV}_A-\delta^{LSDV}_B)$.

In matrix form, we can thus rewrite the LSDV model transformed by the application of the Frich-Waugh theorem as follows:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_{1,B}-\bar{Y}_1 \\	\vdots \\	Y_{N,B}-\bar{Y}_N \\Y_{1,A}-\bar{Y}_1 \\	\vdots \\	Y_{N,A}-\bar{Y}_N \end{array}\right)}_{Y^{LSDV}_r} & =
    \underbrace{\left(\begin{array}{ccc}
      1  & 0 & -\bar{D}_1\\
      \vdots & \vdots & \vdots \\
      1 & 0 & -\bar{D}_N \\
      0 & 1 & D_1-\bar{D}_1\\
      \vdots & \vdots & \vdots \\
      0 & 1 & D_N-\bar{D}_N
    \end{array}\right)}_{X^{LSDV}_r}
  \underbrace{\left(\begin{array}{c}	\tilde{\delta}^{LSDV}_B \\ \tilde{\delta}^{LSDV}_A \\	\beta^{LSDV} \end{array}\right)}_{\Theta^{LSDV}_r} +
  \underbrace{\left(\begin{array}{c}	\epsilon^{LSDV}_{1,B}-\bar{\epsilon}^{LSDV}_{1} \\	\vdots \\	\epsilon^{LSDV}_{N,B}-\bar{\epsilon}^{LSDV}_{N} \\ \epsilon^{LSDV}_{1,A}-\bar{\epsilon}^{LSDV}_{1} \\	\vdots \\	\epsilon^{LSDV}_{N,A}-\bar{\epsilon}^{LSDV}_{N} \end{array}\right)}_{\epsilon^{LSDV}_r}
\end{align*}

This is very close to the formula for the Within estimator we have seen above.
The only difference is that we have two time fixed effects instead of a constant and the **After** time fixed effect.
We are going to solve for the estimator in a very similar way.
First:

\begin{align*}
  {X^{LSDV}_r}'X^{LSDV}_r & = N\underbrace{\left(\begin{array}{ccc}
                    1 &  0 & -\frac{\bar{D}}{2}\\
                    0 & 1  & \frac{\bar{D}}{2} \\
                    -\frac{\bar{D}}{2} & \frac{\bar{D}}{2} & \frac{\bar{D}}{2}
            \end{array}\right)}_{{x^{LSDV}_r}'x^{LSDV}_r}
\end{align*}

The determinant of ${x^{LSDV}_r}'x^{LSDV}_r$ is:

\begin{align*}
  \det({x^{LSDV}_r}'x^{LSDV}_r) & = \frac{1}{2}\bar{D}(1-\bar{D})
\end{align*}

and its adjoint matrix is:

\begin{align*}
  \tilde{{x^{LSDV}_r}'x^{LSDV}_r} & = \left(\begin{array}{ccc}
                    \frac{1}{2}\bar{D}(1-\frac{1}{2}\bar{D}) & - \frac{1}{4}\bar{D}^2 & \frac{1}{2}\bar{D}\\
                    - \frac{1}{4}\bar{D}^2 & \frac{1}{2}\bar{D}(1-\frac{1}{2}\bar{D})  & -\frac{1}{2}\bar{D} \\
                    \frac{1}{2}\bar{D} & -\frac{1}{2}\bar{D} & 1
            \end{array}\right).
\end{align*}

Finally, we have:

\begin{align*}
  {X^{LSDV}_r}'Y^{LSDV}_r & = \left(\begin{array}{c}
                \sum_{i=1}^N(Y_{i,B}-\bar{Y}_i)\\
                \sum_{i=1}^N(Y_{i,A}-\bar{Y}_i) \\
                -\sum_{i=1}^N\bar{D}_i(Y_{i,B}-\bar{Y}_i)+\sum_{i=1}^N(D_i-\bar{D}_i)(Y_{i,A}-\bar{Y}_i)
            \end{array}\right) \\
                          & = \left(\begin{array}{c}
               -\frac{1}{2}N(\bar{Y}_A-\bar{Y}_B)\\
               \frac{1}{2}N(\bar{Y}_A-\bar{Y}_B)\\
               \frac{1}{2}N\bar{D}(\bar{Y}_A^1-\bar{Y}_B^1)
            \end{array}\right)
\end{align*}

Using the fact that $\hat{\Theta}^{LSDV}_r=({X^{LSDV}_r}'X^{LSDV}_r)^{-1}{X^{LSDV}_r}'Y^{LSDV}_r$, we have:

\begin{align*}
  \hat{\beta}^{LSDV} & = \frac{2}{N\bar{D}(1-\bar{D})}\left[-\frac{\bar{D}N}{2}(\bar{Y}_A-\bar{Y}_B)+\frac{\bar{D}N}{2}(\bar{Y}_A^1-\bar{Y}_B^1)\right] \\
                    & =\frac{1}{1-\bar{D}}\left[\bar{Y}_A^1-\bar{Y}_B^1-(1-\bar{D})(\bar{Y}^0_A-\bar{Y}^0_B)-\bar{D}(\bar{Y}_A^1-\bar{Y}_B^1)\right]\\
                    & =\frac{1}{1-\bar{D}}\left[(1-\bar{D})(\bar{Y}_A^1-\bar{Y}_B^1)-(1-\bar{D})(\bar{Y}^0_A-\bar{Y}^0_B)\right]\\
                    & =\bar{Y}_A^1-\bar{Y}_B^1-(\bar{Y}^0_A-\bar{Y}^0_B).
\end{align*}

The second equality uses the fact that $\bar{Y}_A-\bar{Y}_B=(1-\bar{D})(\bar{Y}^0_A-\bar{Y}^0_B)+\bar{D}(\bar{Y}_A^1-\bar{Y}_B^1)$.
This proves the result.

**To Do: the AP and LC estimators**

### Proof of Theorem \@ref(thm:asympnoiseDIDCross) {#proofasympnoiseDIDCross}

The DID model in repeated cross sections can be written in the following matrix form:

\begin{align*}
  \underbrace{\left(\begin{array}{c}  Y_{1,B} \\	\vdots \\	Y_{N_B,B} \\Y_{1,A} \\	\vdots \\	Y_{N_A,A} \end{array}\right)}_{Y} & =
    \underbrace{\left(\begin{array}{cccc}	1 & D^B_{1} & T_{1,B} & D^B_{1}T_{1,B}\\	\vdots & \vdots & \vdots & \vdots\\	1 & D^B_{N_B} & T_{N_B,B} & D^B_{N_B}T_{N_B,B} \\
                                        1 & D^A_{1} & T_{1,A} & D^A_{1}T_{1,A}\\	\vdots & \vdots & \vdots & \vdots\\	1 & D^A_{N_A} & T_{N_A,A} & D^A_{N_A}T_{N_A,A}\end{array}\right)}_{X}
  \underbrace{\left(\begin{array}{c}	\alpha \\ \mu \\ \delta \\	\beta \end{array}\right)}_{\Theta} +
  \underbrace{\left(\begin{array}{c}	\epsilon_{1,B} \\	\vdots \\	\epsilon_{N_B,B} \\ \epsilon_{1,A} \\	\vdots \\	\epsilon_{N_A,A} \end{array}\right),}_{\epsilon}
\end{align*}

where $D^B_{i}$ and $D^A_{i}$ denote the actual treatment status in period $A$ of individuals observed in periods $B$ and $A$ respectively and $N_B$ and $N_A$ are the numbers of units observed in periods $B$ and $A$ respectively.

Using the beginning of the proof of Lemma \@ref(lem:asympOLS), we know that: $\sqrt{N}(\hat{\Theta}_{OLS}-\Theta)=N(X'X)^{-1}\frac{\sqrt{N}}{N}X'\epsilon$.
Using Slutsky's Theorem, we know that we can study both terms separately (see the same proof of Lemma \@ref(lem:asympOLS)). 
Let's start with $N(X'X)^{-1}$.
Using the fact that $T_{i,B}=0$ and $T_{i,A}=1$, $\forall i$, we can write matrix $X$ as follows:

\begin{align*}
  X & = \left(\begin{array}{cccc}	1 & D^B_{1} & 0 & 0\\	\vdots & \vdots & \vdots & \vdots\\	1 & D^B_{N_B} & 0 & 0 \\
                                        1 & D^A_{1} & 1 & D^A_{1}\\	\vdots & \vdots & \vdots & \vdots\\	1 & D^A_{N_A} & 1 & D^A_{N_A}\end{array}\right)
\end{align*}

Doing some matrix multiplication, we have:

\begin{align*}
  X'X & = N_A\underbrace{\left(\begin{array}{cccc}
                    k+1 & k\bar{D}_B+\bar{D}_A & 1 & \bar{D}_A\\
                    k\bar{D}_B+\bar{D}_A & k\bar{D}_B+\bar{D}_A & \bar{D}_A & \bar{D}_A \\
                    1 & \bar{D}_A & 1 & \bar{D}_A\\
                    \bar{D}_A & \bar{D}_A & \bar{D}_A & \bar{D}_A
            \end{array}\right)}_{x'x}
\end{align*}

with $\bar{D}_t=\frac{1}{N_t}\sum_{i=1}^{N_t}D^t_i$, $k=\frac{N_B}{N_A}$, and using the fact that $(D^t_i)^2=D^t_i$ since $D^t_i\in\left\{0,1\right\}$.
Using results on the inverse of a 4 by 4 matrix presented [here](https://semath.info/src/inverse-cofactor-ex4.html) and collecting terms patiently, we find that the determinant of $x'x$ is equal to:

\begin{align*}
  \det(x'x) & = k^2\pi\bar{D}_A^2(1-\bar{D}_A)(1-\pi\bar{D}_A),
\end{align*}
with $\pi=\frac{\bar{D}_B}{\bar{D}_A}$, and its adjugate is equal to:

\begin{align*}
  \tilde{x'x} & = k\pi\bar{D}_A(1-\bar{D}_A)
                  \left(\begin{array}{cccc}
                    \bar{D}_A & -\bar{D}_A & -\bar{D}_A & \bar{D}_A\\
                    -\bar{D}_A & \frac{1}{\pi} & \bar{D}_A & -\frac{1}{\pi} \\
                    -\bar{D}_A & \bar{D}_A & \bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A} & -\bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\\
                    \bar{D}_A & -\frac{1}{\pi} & -\bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A} & k\frac{1-\pi\bar{D}_A}{1-\bar{D}_A}+\frac{1}{\pi}
            \end{array}\right)
\end{align*}

We finally have that $N_A(X'X)^{-1}=\frac{1}{\det(x'x)}\tilde{x'x}$.
Taking the $\text{plim}$ with respect to $N_A$, we have that:

\begin{align*}
  \text{plim}N_A(X'X)^{-1} & = \frac{1}{kp(1-p)}
                  \left(\begin{array}{cccc}
                    p & -p & -p & p\\
                    -p & 1 & p & -1 \\
                    -p & p & p(k+1) & -p(k+1)\\
                    p & -1 & -p(k+1) & k+1
            \end{array}\right)
\end{align*}

The result comes from $\text{plim}\bar{D}_B=\text{plim}\bar{D}_A=\Pr(D_i=1)=p$, according to the Law of Large Numbers, and thus, using Slutsky's Theorem, $\text{plim}\pi=1$.

Let us now derive the asymptotic distribution of $\frac{\sqrt{N}}{N}X'\epsilon$.
In order to do that, we need to know the coefficients of the OLS DID model in repeated cross sections of different sizes.
They probably are the same that with a panel, but we still need to check.
We have that:

\begin{align*}
  X'Y & = N_A\left(\begin{array}{c}
              k\bar{Y}_B+\bar{Y}_A \\
              \bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)\\
              \bar{Y}_A \\
              \bar{D}_A\bar{Y}^1_A
            \end{array}\right)
\end{align*}

Using the fact that $\bar{Y}_t = \bar{D}_t\bar{Y}^1_t+(1-\bar{D}_t)\bar{Y}^0_t$, we have that:

\begin{align*}
  X'Y & = N_A\left(\begin{array}{c}
              \underbrace{k\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}_A(k\pi(\bar{Y}^1_B-\bar{Y}^0_B)+\bar{Y}^1_A-\bar{Y}^0_A)}_{\mathbf{A}} \\
              \underbrace{\bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)}_{\mathbf{B}}\\
              \underbrace{\bar{Y}^0_A+\bar{D}_A(\bar{Y}^1_A-\bar{Y}^0_A)}_{\mathbf{C}} \\
              \underbrace{\bar{D}_A\bar{Y}^1_A}_{\mathbf{D}}
            \end{array}\right)
\end{align*}

Using the fact that $(X'X)^{-1}=\frac{1}{N_A}\frac{\tilde{x'x}}{\det(x'x)}$, we have:

\begin{align*}
  \hat{\Theta}^{OLS} & = (X'X)^{-1}X'Y \\
         & = \frac{1}{\bar{D}_Ak(1-\pi\bar{D}_A)}
            \left(\begin{array}{c}
              \bar{D}_A(\mathbf{A}-\mathbf{B}-\mathbf{C}+\mathbf{D}) \\
              -\bar{D}_A\mathbf{A}+\frac{\mathbf{B}}{\pi}+\bar{D}_A\mathbf{C}-\frac{\mathbf{D}}{\pi} \\
              \bar{D}_A(-\mathbf{A}+\mathbf{B}+\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\mathbf{C}-\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\mathbf{D})\\
              \bar{D}_A\mathbf{A}-\frac{\mathbf{B}}{\pi}-\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\bar{D}_A\mathbf{C}+(k\frac{1-\pi\bar{D}_A}{1-\bar{D}_A}+\frac{1}{\pi})\mathbf{D}
            \end{array}\right)
\end{align*}

Let's take each term in turn:

\begin{align*}
  \hat{\alpha}^{OLS} & = \frac{1}{k(1-\pi\bar{D}_A)}
            \left(k\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}_A(k\pi(\bar{Y}^1_B-\bar{Y}^0_B)+\bar{Y}^1_A-\bar{Y}^0_A) - \bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)\right.\\
                  & \phantom{\frac{1}{k(1-\pi\bar{D}_A)}\left(\right.}
                  \left. - \bar{Y}^0_A-\bar{D}_A(\bar{Y}^1_A-\bar{Y}^0_A)+\bar{D}_A\bar{Y}^1_A\right)\\
                  & = \frac{1}{k(1-\pi\bar{D}_A)}
            \left(\bar{Y}^0_B(k-k\pi\bar{D}_A)+
                  \bar{Y}^0_A(1-\bar{D}_A-1+\bar{D}_A)+
                  \bar{Y}^1_B(k\pi\bar{D}_A-k\pi\bar{D}_A)+ \right.\\
                  & \phantom{\frac{1}{k(1-\pi\bar{D}_A)}\left(\right.}\left. \bar{Y}^1_A(\bar{D}_A-\bar{D}_A-\bar{D}_A+\bar{D}_A)\right) \\
                  & = \bar{Y}^0_Bk\frac{1-\pi\bar{D}_A}{k(1-\pi\bar{D}_A)}\\
                  & = \bar{Y}^0_B
\end{align*}

\begin{align*}
  \hat{\mu}^{OLS} & = \frac{1}{k\bar{D}_A(1-\pi\bar{D}_A)}
            \left(-\bar{D}_A(k\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}_A(k\pi(\bar{Y}^1_B-\bar{Y}^0_B)+\bar{Y}^1_A-\bar{Y}^0_A))\right.\\
            & \phantom{= \frac{1}{k\bar{D}_A(1-\pi\bar{D}_A)}}
            \left.+\frac{\bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)}{\pi}+\bar{D}_A(\bar{Y}^0_A+\bar{D}_A(\bar{Y}^1_A-\bar{Y}^0_A))-\frac{\bar{D}_A\bar{Y}^1_A}{\pi}\right)\\
            & = \frac{1}{k\bar{D}_A(1-\pi\bar{D}_A)}
            \left(-\bar{D}_Ak\bar{Y}^0_B(1-\pi\bar{D}_A)-\bar{Y}^0_A\bar{D}_A(1-\bar{D}_A-1+\bar{D}_A)\right.\\
            & \phantom{= \frac{1}{k\bar{D}_A(1-\pi\bar{D}_A)}}
            \left.+\bar{D}_Ak\bar{Y}^1_B(1-\pi\bar{D}_A)+\bar{Y}^1_A(-\bar{D}_A^2+\frac{\bar{D}_A}{\pi}+\bar{D}_A^2-\frac{\bar{D}_A}{\pi})\right) \\
            & = \frac{k\bar{D}_A(1-\pi\bar{D}_A)}{k\bar{D}_A(1-\pi\bar{D}_A)}(\bar{Y}^1_B-\bar{Y}^0_B)\\
            & = \bar{Y}^1_B-\bar{Y}^0_B
\end{align*}

\begin{align*}
  \hat{\delta}^{OLS} & = \frac{1}{k(1-\pi\bar{D}_A)}\left(-(k\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}_A(k\pi(\bar{Y}^1_B-\bar{Y}^0_B)+\bar{Y}^1_A-\bar{Y}^0_A))\right. \\
                    & \phantom{=\frac{1}{k(1-\pi\bar{D}_A)}}+\bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)+\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}(\bar{Y}^0_A+\bar{D}_A(\bar{Y}^1_A-\bar{Y}^0_A))\\
                    & \phantom{=\frac{1}{k(1-\pi\bar{D}_A)}}\left.-\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\bar{D}_A\bar{Y}^1_A\right) \\
                    & = \frac{1}{k(1-\pi\bar{D}_A)}\left(-\bar{Y}^0_Bk(1-\pi\bar{D}_A)-\bar{Y}^0_A(1-\bar{D}_A-(k+1-\bar{D}_A(k\pi+1)))\right.\\
                    & \phantom{=\frac{1}{k(1-\pi\bar{D}_A)}}\left.+\bar{Y}^1_B(-k\pi\bar{D}_A+k\pi\bar{D}_A)+\bar{Y}^1_A(-\bar{D}_A+\bar{D}_A+\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}(\bar{D}_A-\bar{D}_A))\right)\\
                    & = \frac{1}{k(1-\pi\bar{D}_A)}\left(-\bar{Y}^0_Bk(1-\pi\bar{D}_A)+\bar{Y}^0_Ak(1-\pi\bar{D}_A)\right)\\
                    & = \bar{Y}^0_A-\bar{Y}^0_B
\end{align*}

\begin{align*}
  \hat{\beta}^{OLS} & =\frac{1}{\bar{D}_Ak(1-\pi\bar{D}_A)}\left(\bar{D}_A(k\bar{Y}^0_B+\bar{Y}^0_A+\bar{D}_A(k\pi(\bar{Y}^1_B-\bar{Y}^0_B)+\bar{Y}^1_A-\bar{Y}^0_A))-\frac{\bar{D}_A(k\pi\bar{Y}^1_B+\bar{Y}^1_A)}{\pi}\right.\\
                    & \phantom{ =\frac{1}{\bar{D}_Ak(1-\pi\bar{D}_A)}}\left.-\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\bar{D}_A(\bar{Y}^0_A+\bar{D}_A(\bar{Y}^1_A-\bar{Y}^0_A))+(k\frac{1-\pi\bar{D}_A}{1-\bar{D}_A}+\frac{1}{\pi})\bar{D}_A\bar{Y}^1_A\right) \\
                    & = \frac{1}{\bar{D}_Ak(1-\pi\bar{D}_A)}\left(\bar{Y}^0_B\bar{D}_Ak(1-\pi\bar{D}_A)+\bar{Y}^0_A\bar{D}_A(1-\bar{D}_A-(k+1-\bar{D}_A(k\pi+1)))-\bar{Y}^1_B\bar{D}_Ak(1-\pi\bar{D}_A)\right.\\
                    & \phantom{= \frac{1}{\bar{D}_Ak(1-\pi\bar{D}_A)}}\left.+\bar{Y}^1_A\bar{D}_A(\bar{D}_A-\frac{1}{\pi}-\bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}+k\frac{1-\pi\bar{D}_A}{1-\bar{D}_A}+\frac{1}{\pi})\right)\\
                    & = \frac{1}{k(1-\pi\bar{D}_A)}\left(-k(1-\pi\bar{D}_A)(\bar{Y}^1_B-\bar{Y}^0_B)-k(1-\pi\bar{D}_A)\bar{Y}^0_A+  k(1-\pi\bar{D}_A)\bar{Y}^1_A\right)\\
                    & = \bar{Y}^1_A-\bar{Y}^0_A-(\bar{Y}^1_B-\bar{Y}^0_B).
\end{align*}

So it is confirmed that OLS estimation of the DID model in repeated cross sections of different sizes estimates the same parameters than in panel data.
Thanks to the Law of Large Numbers, we know that:

\begin{align*}
  \text{plim}\hat\Theta^{OLS} & =\left(\begin{array}{c}
              \esp{Y^0_{i,B}|D_i=0}\\
              \esp{Y^0_{i,B}|D_i=1}-\esp{Y^0_{i,B}|D_i=1}\\
              \esp{Y^0_{i,A}-Y^0_{i,B}|D_i=0}\\
              \esp{Y^1_{i,A}-Y^0_{i,B}|D_i=1}-\esp{Y^0_{i,A}-Y^0_{i,B}|D_i=0}
            \end{array}\right),
\end{align*}

where the $\text{plim}$ is taken over $N=N_A+N_B$.

In order to study more easily the DID model as estimated by OLS, we are going to rewrite it as a pure cross sectional model:

\begin{align*}
  Y_j & = \alpha + \mu D_j + \delta T_j + \beta D_jT_j + \epsilon_j,
\end{align*}

where $j=i$ when $t=B$ and $j=N_B+i$ when $t=A$, $D_j=D_i^t$, $T_j=T_{i,t}$ and $Y_j=Y_{i,t}$.
In that case, we are assuming that $T_i$ is a random variable, whereas in real life, the sample is stratified with respect to $T_i$.
We will treat this case in the stratification section.
For now, assuming that time is sampled as a usual random variable is a useful simplification.

From what we have proven above, we know that:

\begin{align*}
  \epsilon_{j} & = Y_{j}-\left(\esp{Y^0_{j}|D_j=0,T_j=0}+D_j(\esp{Y^0_{j}|D_j=1,T_j=0}-\esp{Y^0_{j}|D_j=0,T_j=0})\right.\\
                & \phantom{=Y_{j}-\left(\right.}+T_j(\esp{Y^0_{j}|D_j=0,T_j=1}-\esp{Y^0_{j}|D_j=0,T_j=0})\\
                  & \phantom{=Y_{j}-\left(\right.}+D_jT_j(\esp{Y^1_{j}|D_j=1,T_j=1}-\esp{Y^0_{j}|D_j=1,T_j=0}\\
                  & \phantom{=Y_{j}-\left(\right.+D_jT_j}\left.-(\esp{Y^0_{j}|D_j=0,T_j=1}-\esp{Y^0_{j}|D_j=0,T_j=0}))\right)
\end{align*}

With this notation, and $N=N_A+N_B$, we have:

\begin{align*}
  \frac{\sqrt{N}}{N}X'\epsilon & =\sqrt{N}\left(\begin{array}{c}
              \frac{1}{N}\sum_{i=1}^N\epsilon_{j} \\
              \frac{1}{N}\sum_{i=1}^ND_j\epsilon_{j} \\
              \frac{1}{N}\sum_{i=1}^NT_j\epsilon_{j} \\
              \frac{1}{N}\sum_{i=1}^ND_jT_j\epsilon_{j} 
            \end{array}\right).
\end{align*}

In order to be able to use the vector CLT in order to study the distribution of these quantities, we need first to compute the expectation of these variables.
Let us first start with $\esp{D_jT_j\epsilon_{j}}$:

\begin{align*}
  \esp{D_jT_j\epsilon_{j}} & =\esp{\epsilon_{j}|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1)\\
                          & = 0,
\end{align*}

where the first equality follows from Bayes' Law and the second equality from the definition of $\epsilon_{j}$.
Using the same reasoning, we have:

\begin{align*}
  \esp{D_j\epsilon_{j}} & =\esp{\epsilon_{j}|D_j=1,T_j=1}\Pr(T_j=1|D_j=1)+\esp{\epsilon_{j}|D_j=1,T_j=0}\Pr(T_j=0|D_j=1)\\
                          & = 0\\
  \esp{T_j\epsilon_{j}} & =\esp{\epsilon_{j}|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)+\esp{\epsilon_{j}|D_j=0,T_j=1}\Pr(D_j=0|T_j=1)\\
                          & = 0\\
  \esp{\epsilon_{j}} & =\esp{\epsilon_{j}|T_j=1}\Pr(T_j=1)+\esp{\epsilon_{j}|T_j=0}\Pr(T_j=0)\\
                          & = (\esp{\epsilon_{j}|T_j=0,D_j=1}\Pr(D_j=1|T_j=0)+\esp{\epsilon_{j}|T_j=0,D_j=0}\Pr(D_j=0|T_j=0))\Pr(T_j=0)\\
                          & = 0.
\end{align*}

Using the vector version of the CLT that we have already invoked in the proof of Lemma \@ref(lem:asympOLS), we have that $\sqrt{N}\frac{X'\epsilon}{N}\sim\mathcal{N}((0,0,0,0),\mathbf{V_{x\epsilon}})$ with:

\begin{align*}
  \mathbf{V_{x\epsilon}} & = \esp{\left(\begin{array}{c}  \epsilon_i  \\	\epsilon_iD_i \\ \epsilon_iT_i \\ \epsilon_iD_iT_i \end{array}\right)
                                  \left(\begin{array}{cccc}	\epsilon_i &	\epsilon_iD_i &  \epsilon_iT_i &  \epsilon_iD_iT_i \end{array}\right)}
- \esp{\left(\begin{array}{c}  \epsilon_i  \\	\epsilon_iD_i \\ \epsilon_iT_i \\ \epsilon_iD_iT_i \end{array}\right)}
                    \esp{\left(\begin{array}{cccc}	\epsilon_i &	\epsilon_iD_i &  \epsilon_iT_i &  \epsilon_iD_iT_i \end{array}\right)}\\
                & = \esp{\epsilon_i^2\left(\begin{array}{cccc}
                                              1 & D_i &	T_i & D_iT_i \\
                                              D_i & D_i &	D_iT_i & D_iT_i \\
                                              T_i & D_iT_i &	T_i & D_iT_i \\
                                              D_iT_i & D_iT_i &	D_iT_i & D_iT_i
                                            \end{array}\right)},
\end{align*}

where we made use of the fact that $T_i^2=T_i$ and $D_i^2=D_i$. 

Before we can use the Delta Method to derive the distribution of the OLS DID estimator, we need to compute $\text{plim}N(X'X)-1$ as a function of $N$ and not $N_A$, as we did before.
In order to obtain that without redoing the matrix inversion all over again (which is pretty awful without the trick of factoring $N_A$), we are going to use the fact that the proportion of observations belonging to period $A$ is equal to $\bar{T}_A=\frac{N_A}{N}=\sum_{j=1}^NT_j$, and the proportion of observations belonging to period $B$ is equal to $1-\bar{T}_A$. 
We also have that $k=\frac{N_B}{N_A}=\frac{(1-\bar{T}_A)N}{\bar{T}_AN}=\frac{1-\bar{T}_A}{\bar{T}_A}$.
Finally, note that $\pi=\frac{\bar{D}_B}{\bar{D}_A}$.
As a consequence of that and of our previous computations, we have that:

\begin{align*}
  (X'X)^{-1} & = \frac{1}{N_A}\frac{1}{k\bar{D}_A(1-\pi\bar{D}_A)}
                  \left(\begin{array}{cccc}
                    \bar{D}_A & -\bar{D}_A & -\bar{D}_A & \bar{D}_A\\
                    -\bar{D}_A & \frac{1}{\pi} & \bar{D}_A & -\frac{1}{\pi} \\
                    -\bar{D}_A & \bar{D}_A & \bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A} & -\bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A}\\
                    \bar{D}_A & -\frac{1}{\pi} & -\bar{D}_A\frac{k+1-\bar{D}_A(k\pi+1)}{1-\bar{D}_A} & k\frac{1-\pi\bar{D}_A}{1-\bar{D}_A}+\frac{1}{\pi}
            \end{array}\right) \\
          & =   \frac{1}{N\bar{T}_A}\frac{1}{\frac{1-\bar{T}_A}{\bar{T}_A}\bar{D}_A(1-\frac{\bar{D}_B}{\bar{D}_A}\bar{D}_A)}\\
          & \phantom{=}
                  \left(\begin{array}{cccc}
                    \bar{D}_A & -\bar{D}_A & -\bar{D}_A & \bar{D}_A\\
                    -\bar{D}_A & \frac{\bar{D}_A}{\bar{D}_B} & \bar{D}_A & -\frac{\bar{D}_A}{\bar{D}_B} \\
                    -\bar{D}_A & \bar{D}_A & \bar{D}_A\frac{\frac{1-\bar{T}_A}{\bar{T}_A}+1-\bar{D}_A(\frac{1-\bar{T}_A}{\bar{T}_A}\frac{\bar{D}_B}{\bar{D}_A}+1)}{1-\bar{D}_A} & -\bar{D}_A\frac{\frac{1-\bar{T}_A}{\bar{T}_A}+1-\bar{D}_A(\frac{1-\bar{T}_A}{\bar{T}_A}\frac{\bar{D}_B}{\bar{D}_A}+1)}{1-\bar{D}_A}\\
                    \bar{D}_A & -\frac{\bar{D}_A}{\bar{D}_B} & -\bar{D}_A\frac{\frac{1-\bar{T}_A}{\bar{T}_A}+1-\bar{D}_A(\frac{1-\bar{T}_A}{\bar{T}_A}\frac{\bar{D}_B}{\bar{D}_A}+1)}{1-\bar{D}_A} & \frac{1-\bar{T}_A}{\bar{T}_A}\frac{1-\frac{\bar{D}_B}{\bar{D}_A}\bar{D}_A}{1-\bar{D}_A}+\frac{\bar{D}_A}{\bar{D}_B}
            \end{array}\right) \\
           & =   \frac{1}{N}\frac{1}{(1-\bar{T}_A)(1-\bar{D}_B)}\\
          & \phantom{=}
                  \left(\begin{array}{cccc}
                    1 & -1 & -1 & 1\\
                    -1 & \frac{1}{\bar{D}_B} & 1 & -\frac{1}{\bar{D}_B} \\
                    -1 & 1 & \frac{1-\bar{D}_B+\bar{T}_A(\bar{D}_B-\bar{D}_A)}{\bar{T}_A(1-\bar{D}_A)} & -\frac{1-\bar{D}_B+\bar{T}_A(\bar{D}_B-\bar{D}_A)}{\bar{T}_A(1-\bar{D}_A)}\\
                    1 & -\frac{1}{\bar{D}_B} & -\frac{1-\bar{D}_B+\bar{T}_A(\bar{D}_B-\bar{D}_A)}{\bar{T}_A(1-\bar{D}_A)} & \frac{1}{\bar{D}_A}\frac{1-\bar{T}_A}{\bar{T}_A}\frac{1-\bar{D}_B}{1-\bar{D}_A}+\frac{1}{\bar{D}_B}
            \end{array}\right),
\end{align*}

because:

\begin{align*}
\frac{\frac{1-\bar{T}_A}{\bar{T}_A}+1-\bar{D}_A(\frac{1-\bar{T}_A}{\bar{T}_A}\frac{\bar{D}_B}{\bar{D}_A}+1)}{1-\bar{D}_A} & = \frac{1+\frac{1-\bar{T}_A}{\bar{T}_A}-\frac{1-\bar{T}_A}{\bar{T}_A}\bar{D}_B+ \bar{D}_A}{1-\bar{D}_A} \\
= & \frac{\bar{T}_A+1-\bar{T}_A-\bar{D}_B+\bar{T}_A\bar{D}_B+ \bar{D}_A\bar{T}_A}{\bar{T}_A(1-\bar{D}_A)}\\
= & \frac{1-\bar{D}_B+\bar{T}_A(\bar{D}_B-\bar{D}_A)}{\bar{T}_A(1-\bar{D}_A)}.
\end{align*}

As a consequence, we have:

\begin{align*}
  \text{plim}N(X'X)^{-1} & = \frac{1}{(1-p_A)(1-p)}
                  \left(\begin{array}{cccc}
                    1 & -1 & -1 & 1\\
                    -1 & \frac{1}{p} & 1 & -\frac{1}{p} \\
                    -1 & 1 & \frac{1}{p_A} & -\frac{1}{p_A} \\
                    1 & -\frac{1}{p} & -\frac{1}{p_A}  & \frac{1}{pp_A}
            \end{array}\right),
\end{align*}

using the Law of Large Numbers, Slutsky's Theorem and the fact that $\text{plim}\bar{T}_A=p_A$, the proportion of observations stemming from the After period, $\text{plim}\bar{D}_A=\text{plim}\bar{D}_B=p$ and the fact that $\frac{1}{p}\frac{1-p_A}{p_A}+\frac{1}{p}=\frac{1}{pp_A}$.

Now, we can derive the asymptotic distribution of $\sqrt{N}(\hat{\Theta}_{OLS}-\Theta)=N(X'X)^{-1}\frac{\sqrt{N}}{N}X'\epsilon$.
Using the Delta Method, we have that  $\sqrt{N}(\hat{\Theta}_{OLS}-\Theta)\stackrel{d}{\rightarrow}\mathcal{N}\left((0,0,0,0),\sigma_{XX}^{-1}\mathbf{V_{x\epsilon}}\sigma_{XX}^{-1}\right)$.
So we're in for a treat: deriving the lower diagonal term in the quadratic form $\sigma_{XX}^{-1}\mathbf{V_{x\epsilon}}\sigma_{XX}^{-1}$.

Let us start.
We first need the four terms on the last line of $(1-p_A)^2(1-p)^2\sigma_{XX}^{-1}\mathbf{V_{x\epsilon}}=(\mathbf{A},\mathbf{B},\mathbf{C},\mathbf{D})$ (the squared terms in the beginning are accounting for the constant terms in the matrix multiplication):

\begin{align*}
  \mathbf{A}& = \esp{\epsilon_j^2} -\frac{1}{p}\esp{\epsilon_j^2D_j} -\frac{1}{p_A}\esp{\epsilon_j^2T_j} + \frac{1}{pp_A}\esp{\epsilon_j^2D_jT_j}\\
            & =  \esp{\epsilon_j^2|D_j=0,T_j=0}\Pr(D_j=0|T_j=0)\Pr(T_j=0)+\esp{\epsilon_j^2|D_j=1,T_j=0}\Pr(D_j=1|T_j=0)\Pr(T_j=0)\\
            & \phantom{=}+\esp{\epsilon_j^2|D_j=0,T_j=1}\Pr(D_j=0|T_j=1)\Pr(T_j=1)+\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1) \\
            & \phantom{=}-\frac{1}{p}\esp{\epsilon_j^2|D_j=1}\Pr(D_j=1) -\frac{1}{p_A}\esp{\epsilon_j^2|T_j=1}\Pr(T_j=1) \\
            & \phantom{=}+ \frac{1}{pp_A}\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1)\\
            & =  \esp{\epsilon_j^2|D_j=0,T_j=0}(1-p)(1-p_A)+\esp{\epsilon_j^2|D_j=1,T_j=0}p(1-p_A)\\
            & \phantom{=}+\esp{\epsilon_j^2|D_j=0,T_j=1}(1-p)p_A+\esp{\epsilon_j^2|D_j=1,T_j=1}pp_A \\
            & \phantom{=}-\esp{\epsilon_j^2|D_j=1} -\esp{\epsilon_j^2|T_j=1} \\
            & \phantom{=}+ \esp{\epsilon_j^2|D_j=1,T_j=1}\\
            & =  \esp{\epsilon_j^2|D_j=0,T_j=0}(1-p)(1-p_A)+\esp{\epsilon_j^2|D_j=1,T_j=0}p(1-p_A)\\
            & \phantom{=}+\esp{\epsilon_j^2|D_j=0,T_j=1}(1-p)p_A+\esp{\epsilon_j^2|D_j=1,T_j=1}pp_A \\
            & \phantom{=}-\esp{\epsilon_j^2|D_j=1,T_j=0}(1-p_A)-\esp{\epsilon_j^2|D_j=1,T_j=1}p_A\\
            & \phantom{=}-\esp{\epsilon_j^2|D_j=0,T_j=1}(1-p)-\esp{\epsilon_j^2|D_j=1,T_j=1}p \\
            & \phantom{=}+ \esp{\epsilon_j^2|D_j=1,T_j=1}\\
            & =  \esp{\epsilon_j^2|D_j=0,T_j=0}(1-p)(1-p_A)\\
            & \phantom{=}-\esp{\epsilon_j^2|D_j=1,T_j=0}(1-p)(1-p_A)\\
            & \phantom{=}-\esp{\epsilon_j^2|D_j=0,T_j=1}(1-p)(1-p_A)\\
            & \phantom{=}+\esp{\epsilon_j^2|D_j=1,T_j=1}(1-p)(1-p_A)\\
            & = (1-p)(1-p_A)(\sigma_{\epsilon_{0,0}}^2-\sigma_{\epsilon_{1,0}}^2-\sigma_{\epsilon_{0,1}}^2+\sigma_{\epsilon_{1,1}}^2)\\
  \mathbf{B}& = \esp{\epsilon_j^2D_j} -\frac{1}{p}\esp{\epsilon_j^2D_j} -\frac{1}{p_A}\esp{\epsilon_j^2D_jT_j} + \frac{1}{pp_A}\esp{\epsilon_j^2D_jT_j}\\
            & = \esp{\epsilon_j^2D_j}(1-\frac{1}{p})+\esp{\epsilon_j^2D_jT_j}\frac{1}{p_A}(\frac{1}{p}-1) \\
            & = (1-\frac{1}{p})\esp{\epsilon_j^2|D_j=1}\Pr(D_j=1)+\frac{1}{p_A}(\frac{1}{p}-1)\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1) \\
            & = p(1-\frac{1}{p})\left(\esp{\epsilon_j^2|D_j=1,T_j=0}\Pr(T_j=0|D_j=1)+\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(T_j=1|D_j=1)\right)\\
            & \phantom{=}+\frac{1}{p_A}(\frac{1}{p}-1)\sigma_{\epsilon_{1,1}}^2pp_A\\
            & = p(1-\frac{1}{p})\left(\sigma_{\epsilon_{1,0}}^2(1-p_A)+\sigma_{\epsilon_{1,1}}^2p_A\right)+\frac{1}{p_A}(\frac{1}{p}-1)\sigma_{\epsilon_{1,1}}^2pp_A\\
            & = -(1-p)\left(\sigma_{\epsilon_{1,0}}^2(1-p_A)+\sigma_{\epsilon_{1,1}}^2p_A\right)+(1-p)\sigma_{\epsilon_{1,1}}^2\\
            & = (1-p)\left(\sigma_{\epsilon_{1,1}}^2-\sigma_{\epsilon_{1,0}}^2(1-p_A)-\sigma_{\epsilon_{1,1}}^2p_A\right)\\
            & = (1-p)(1-p_A)\left(\sigma_{\epsilon_{1,1}}^2-\sigma_{\epsilon_{1,0}}^2\right) \\
  \mathbf{C}& = \esp{\epsilon_j^2T_j} -\frac{1}{p}\esp{\epsilon_j^2D_jT_j} -\frac{1}{p_A}\esp{\epsilon_j^2T_j} + \frac{1}{pp_A}\esp{\epsilon_j^2D_jT_j}\\
            & = \esp{\epsilon_j^2|T_j=1}\Pr(T_j=1)-\frac{1}{p}\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1)\\
            & \phantom{=}-\frac{1}{p_A}\esp{\epsilon_j^2|T_j=1}\Pr(T_j=1)+\frac{1}{pp_A}\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1)\\
            & = -(1-p_A)(\esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)+\esp{\epsilon_j^2|D_j=0,T_j=1}\Pr(D_j=0|T_j=1))\\
            & \phantom{=}+\esp{\epsilon_j^2|D_j=1,T_j=1}(1-p_A)\\
            & = (1-p_A)(\sigma_{\epsilon_{1,1}}^2(1-p)-(1-p)\sigma_{\epsilon_{0,1}}^2)\\
            & = (1-p)(1-p_A)(\sigma_{\epsilon_{1,1}}^2-\sigma_{\epsilon_{0,1}}^2)\\
  \mathbf{D}& = \esp{\epsilon_j^2D_jT_j} -\frac{1}{p}\esp{\epsilon_j^2D_jT_j} -\frac{1}{p_A}\esp{\epsilon_j^2D_jT_j} + \frac{1}{pp_A}\esp{\epsilon_j^2D_jT_j}\\
            & = \esp{\epsilon_j^2|D_j=1,T_j=1}\Pr(D_j=1|T_j=1)\Pr(T_j=1)(1-\frac{1}{p}-\frac{1}{p_A}+\frac{1}{pp_A})\\
            & = \sigma_{\epsilon_{1,1}}^2(pp_A-p_A-p+1)\\
            & = (1-p)(1-p_A)\sigma_{\epsilon_{1,1}}^2
\end{align*}

since $1-p-p_A+pp_A=(1-p)(1-p_A)$, and where $\sigma_{\epsilon_{d,t}}^2=\esp{\epsilon_j^2|D_j=d,T_j=t}$.
We also make use of the fact that $\Pr(D_j=d|T_j=t)=\Pr(D_j=d)$ and $\Pr(T_j=t|D_j=d)=\Pr(T_j=t)$, that is that the participants and non participants are sampled exactly in the same proportion in both periods.

Let us now obtain $\var{\hat{\beta}^{OLS}}$, the variance of the $\hat{\beta}^{OLS}$ parameter.
It is the last diagonal term of the matrix $\sigma_{XX}^{-1}\mathbf{V_{x\epsilon}}\sigma_{XX}^{-1}$.
We know that:

\begin{align*}
  \var{\hat{\beta}^{OLS}} & = \frac{1}{(1-p)^2(1-p_A)^2}\left(\mathbf{A}-\frac{1}{p}\mathbf{B}-\frac{1}{p_A}\mathbf{C}+\frac{1}{pp_A}\mathbf{D}\right)\\
                          & = \frac{1}{(1-p)(1-p_A)}\left(\sigma_{\epsilon_{0,0}}^2-\sigma_{\epsilon_{1,0}}^2-\sigma_{\epsilon_{0,1}}^2+\sigma_{\epsilon_{1,1}}^2
                                                          -\frac{1}{p}(\sigma_{\epsilon_{1,1}}^2-\sigma_{\epsilon_{1,0}}^2) \right.\\
                          & \phantom{= \frac{1}{(1-p)(1-p_A)}\left(\right.}\left.
                                                          -\frac{1}{p_A}(\sigma_{\epsilon_{1,1}}^2-\sigma_{\epsilon_{0,1}}^2)+ \frac{1}{pp_A}\sigma_{\epsilon_{1,1}}^2\right)\\
                          & = \frac{1}{(1-p)(1-p_A)}\left(\sigma_{\epsilon_{0,0}}^2+\sigma_{\epsilon_{1,0}}^2(-1+\frac{1}{p})+\sigma_{\epsilon_{0,1}}^2(-1+\frac{1}{p_A})+\sigma_{\epsilon_{1,1}}^2(1-\frac{1}{p}-\frac{1}{p_A}+\frac{1}{pp_A})\right)\\
                          & = \frac{1}{(1-p)(1-p_A)}\left(\sigma_{\epsilon_{0,0}}^2+\sigma_{\epsilon_{1,0}}^2\frac{1-p}{p}+\sigma_{\epsilon_{0,1}}^2(\frac{1-p_A}{p_A}+\sigma_{\epsilon_{1,1}}^2\frac{pp_A-p_A-p+1}{pp_A}\right)\\
                          & = \frac{\sigma_{\epsilon_{0,0}}^2}{(1-p)(1-p_A)}+\frac{\sigma_{\epsilon_{1,0}}^2}{p(1-p_A)}+\frac{\sigma_{\epsilon_{0,1}}^2}{(1-p)p_A}+\frac{\sigma_{\epsilon_{1,1}}^2}{pp_A},
\end{align*}

using again the fact that $1-p-p_A+pp_A=(1-p)(1-p_A)$.

Finally, using the formula for $\epsilon_j$, we have:

\begin{align*}
 \sigma_{\epsilon_{0,0}}^2 & = \esp{\epsilon_j^2|D_j=0,T_j=0} \\
                          & = \esp{(Y_j-\esp{Y^0_j|D_j=0,T_j=0})^2|D_j=0,T_j=0}\\
                          & = \esp{(Y^0_{i,B}-\esp{Y^0_{i,B}|D_i=0)^2}|D_i=0}\\
                          & = \var{Y^0_{i,B}|D_i=0}\\
 \sigma_{\epsilon_{1,0}}^2 & = \esp{\epsilon_j^2|D_j=1,T_j=0} \\
                          & = \esp{(Y_j-\esp{Y^0_j|D_j=1,T_j=0})^2|D_j=1,T_j=0}\\
                          & = \esp{(Y^0_{i,B}-\esp{Y^0_{i,B}|D_i=1)^2}|D_i=1}\\
                          & = \var{Y^0_{i,B}|D_i=1}\\
 \sigma_{\epsilon_{0,1}}^2 & = \esp{\epsilon_j^2|D_j=0,T_j=1} \\
                          & = \esp{(Y_j-\esp{Y^0_j|D_j=0,T_j=1})^2|D_j=0,T_j=1}\\
                          & = \esp{(Y^0_{i,A}-\esp{Y^0_{i,A}|D_i=0)^2}|D_i=0}\\
                          & = \var{Y^0_{i,A}|D_i=0}\\
 \sigma_{\epsilon_{1,1}}^2 & = \esp{\epsilon_j^2|D_j=1,T_j=1} \\
                          & = \esp{(Y_j-\esp{Y^1_j|D_j=1,T_j=1})^2|D_j=1,T_j=1}\\
                          & = \esp{(Y^1_{i,A}-\esp{Y^1_{i,A}|D_i=1)^2}|D_i=1}\\
                          & = \var{Y^1_{i,A}|D_i=1}
\end{align*}                          

This proves the result.


### Proof of Theorem \@ref(thm:EquivDIDSApop) {#proofEquivDIDSApop}

The proof uses saturated models as [Angrist and Pischke(2009)](https://press.princeton.edu/books/paperback/9780691120355/mostly-harmless-econometrics).
A saturated model is a model involving only categorical variables where the model has a separate parameter for each various sets of parameter values that
the covariates can take. 
We can check that Sun and Abraham's model is a saturated model. 
Let's start with the model in repeated cross sections (with group fixed effects). 
In the population, excluding the group of individuals that are always treated (adding this group would entail adding a separate dummy for
each date at which they are observed, I leave that as an exercise), with $T=4$ (larger time series do not change the basic result):

\begin{align*} 
\esp{Y_{i,1}|D_i=\infty} & = \alpha \\ 
\esp{Y_{i,2}|D_i=\infty} &= \alpha+\delta_2  \\ 
\esp{Y_{i,3}|D_i=\infty} & = \alpha+\delta_3  \\
\esp{Y_{i,4}|D_i=\infty} & = \alpha+\delta_4  \\ 
\esp{Y_{i,1}|D_i=2} & = \alpha +\mu_2  \\ 
\esp{Y_{i,2}|D_i=2} & = \alpha +\mu_2 +\delta_2 + \beta_{2,0}^{SA}\\ 
\esp{Y_{i,3}|D_i=2} & = \alpha +\mu_2 +\delta_3 + \beta_{2,1}^{SA}  \\
\esp{Y_{i,4}|D_i=2} & = \alpha +\mu_2 +\delta_4 + \beta_{2,2}^{SA}  \\
\esp{Y_{i,1}|D_i=3} & = \alpha +\mu_3 +          \beta_{3,-2}^{SA}   \\
\esp{Y_{i,2}|D_i=3} & = \alpha +\mu_3 + \delta_2   \\ 
\esp{Y_{i,3}|D_i=3} & = \alpha +\mu_3 + \delta_3 + \beta_{3,0}^{SA}  \\ 
\esp{Y_{i,4}|D_i=3} & = \alpha+\mu_3 + \delta_4 + \beta_{3,1}^{SA}  \\ 
\esp{Y_{i,1}|D_i=4} & = \alpha +\mu_4 +\beta_{4,-3}^{SA}   \\ 
\esp{Y_{i,2}|D_i=4} & = \alpha +\mu_4 + \delta_2+\beta_{4,-2}^{SA}   \\ 
\esp{Y_{i,3}|D_i=4} & = \alpha +\mu_4 + \delta_3   \\
\esp{Y_{i,4}|D_i=4} & = \alpha +\mu_4 + \delta_4 + \beta_{4,0}^{SA} 
\end{align*}

The model has 16 parameters to model the 16 different combinations of the regressors. 
It is thus a saturated model.
Let us now state the Linear Conditional Expectation Function Theorem:

```{theorem,LinearCEF,name='Linear Conditional Expectation Function'} 
Let $\esp{Y_i|X_i}=X_i'\Theta^*$ for a $K\times 1$ vector of coefficients $\Theta^*$. Then $\Theta^*=\esp{X_i'X_i}^{-1}\esp{X_i'Y_i}=\Theta^{OLS}$. 
```

Theorem \@ref(thm:LinearCEF) states that the coefficients of a model with a
linear conditional expectation function can be obtained by using OLS. Applying
Theorem \@ref(thm:LinearCEF) to Sun and Abraham's saturated model, we have that:

\begin{align*} 
\alpha & = \esp{Y_{i,1}|D_i=\infty}=\alpha^{OLS}  \\ 
\delta_2 & =\esp{Y_{i,2}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty}=\delta_2^{OLS}  \\ 
\delta_3 &= \esp{Y_{i,3}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty}=\delta_3^{OLS}   \\ 
\delta_4 & = \esp{Y_{i,4}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty}=\delta_4^{OLS}   \\ 
\mu_2 & = \esp{Y_{i,1}|D_i=2}-\esp{Y_{i,1}|D_i=\infty}     =\mu_2^{OLS}   \\ 
\mu_3 & = \esp{Y_{i,2}|D_i=3}-\esp{Y_{i,2}|D_i=\infty}     =\mu_3^{OLS}   \\ 
\mu_4 & = \esp{Y_{i,3}|D_i=4}-\esp{Y_{i,3}|D_i=\infty}     =\mu_4^{OLS}   \\
\beta_{2,0}^{SA} & = \esp{Y_{i,2}|D_i=2}-\esp{Y_{i,1}|D_i=2}-(\esp{Y_{i,2}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty}) =\beta_{2,0}^{OLS} \\ 
\beta_{2,1}^{SA} & = \esp{Y_{i,3}|D_i=2}-\esp{Y_{i,1}|D_i=2}-(\esp{Y_{i,3}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty})=\beta_{2,1}^{OLS} \\ 
\beta_{2,2}^{SA} & = \esp{Y_{i,4}|D_i=2}-\esp{Y_{i,1}|D_i=2}-(\esp{Y_{i,4}|D_i=\infty}-\esp{Y_{i,1}|D_i=\infty})=\beta_{2,2}^{OLS} \\ 
\beta_{3,-2}^{SA} & =\esp{Y_{i,1}|D_i=3}-\esp{Y_{i,2}|D_i=3}-(\esp{Y_{i,1}|D_i=\infty}-\esp{Y_{i,2}|D_i=\infty})=\beta_{3,-2}^{OLS}\\ 
\beta_{3,0}^{SA} & =\esp{Y_{i,3}|D_i=3}-\esp{Y_{i,2}|D_i=3}-(\esp{Y_{i,3}|D_i=\infty}-\esp{Y_{i,2}|D_i=\infty})=\beta_{3,0}^{OLS}\\ 
\beta_{3,1}^{SA} & =\esp{Y_{i,4}|D_i=3}-\esp{Y_{i,2}|D_i=3}-(\esp{Y_{i,4}|D_i=\infty}-\esp{Y_{i,2}|D_i=\infty})=\beta_{3,1}^{OLS}\\ 
\beta_{4,-3}^{SA} & =\esp{Y_{i,1}|D_i=4}-\esp{Y_{i,3}|D_i=4}-(\esp{Y_{i,1}|D_i=\infty}-\esp{Y_{i,3}|D_i=\infty})=\beta_{4,-3}^{OLS}\\ 
\beta_{4,-2}^{SA} & =\esp{Y_{i,2}|D_i=4}-\esp{Y_{i,3}|D_i=4}-(\esp{Y_{i,2}|D_i=\infty}-\esp{Y_{i,3}|D_i=\infty})=\beta_{4,-2}^{OLS}\\ 
\beta_{4,0}^{SA} & =\esp{Y_{i,4}|D_i=4}-\esp{Y_{i,3}|D_i=4}-(\esp{Y_{i,4}|D_i=\infty}-\esp{Y_{i,3}|D_i=\infty})=\beta_{4,0}^{OLS}
\end{align*}

This proves that Sun and Abraham's estimator is actually equal to the individual DID estimators $\beta_{d,\tau}^{SA}=\Delta^{Y}_{DID}(d,\infty,\tau,d-1)$ in the population, which completes the proof for the model with group fixed effects and
$T=4$. 
I leave generalizing this result to any $T$ and to the panel data model with individual fixed effects as an exercise.

### Proof of Theorem \@ref(thm:EquivDIDSAsamp) {#proofEquivDIDSAsamp}

Let us start with Sun and Abraham's model in repeated cross sections, with group fixed effects. 
Here is how we can write this model with four time periods:

\begin{align*} 
Y & = X\Theta + \epsilon 
\end{align*} 
with 
\begin{align*} 
Y & =\left(\begin{array}{c}	Y_{1,1} \\ \vdots \\ Y_{N_1,1}\\ Y_{1,2} \\ \vdots \\Y_{N_2,2}\\ Y_{1,3} \\ \vdots \\ Y_{N_3,3}\\ Y_{1,4} \\ \vdots \\ Y_{N_4,4}
\end{array}\right)  \\ 
X & = \left(\begin{array}{cccccccccccccccc} 
1 & D^2_1 & D^3_1 & D^4_1 & 0 & 0 & 0 & 0 & 0 & 0 & D^3_1 & 0 & 0 & D^4_1 & 0 & 0\\ 
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots &\vdots & \vdots& \vdots & \vdots & \vdots & \vdots \\ 
1 & D^2_{N_1} & D^3_{N_1} & D^4_{N_1} & 0 & 0 & 0 & 0 & 0 & 0 & D^3_{N_1} & 0 & 0 & D^4_{N_1} & 0 & 0\\ 
1 & D^2_1 & D^3_1 & D^4_1 & 1 & 0 & 0 & D^2_1 & 0 & 0 & 0 & 0 & 0 & 0 & D^4_1 &0\\ 
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots &\vdots & \vdots & \vdots & \vdots& \vdots & \vdots & \vdots & \vdots \\ 
1 & D^2_{N_2} & D^3_{N_2} & D^4_{N_2} & 1 & 0 & 0 & D^2_{N_2} & 0 & 0 & 0 & 0 & 0 &0 & D^4_{N_2} & 0\\ 
1 & D^2_1 & D^3_1 & D^4_1 & 0 & 1 & 0 & 0 & D^2_1 & 0 & 0 & D^3_1 & 0 & 0 & 0 & 0\\ 
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots& \vdots & \vdots & \vdots & \vdots \\ 
1 & D^2_{N_3} & D^3_{N_3} & D^4_{N_3} & 0 & 1 & 0 & 0 & D^2_{N_3} & 0 & 0 & D^3_{N_3} & 0 & 0 & 0 & 0\\ 
1 & D^2_1 & D^3_1 & D^4_1 & 0 & 0 & 1 & 0 & 0 & D^2_1 & 0 & 0 & D^3_1 & 0 & 0 & D^4_1\\ 
\vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots & \vdots& \vdots & \vdots & \vdots & \vdots \\ 
1 & D^2_{N_4} & D^3_{N_4} & D^4_{N_4} & 0 & 0 & 1 & 0 & 0 & D^2_{N_4} & 0 & 0 & D^3_{N_4} & 0 & 0 & D^4_{N_4} 
\end{array}\right)\\ 
\Theta & =\left(\begin{array}{c}	
\alpha \\ \mu_2\\ \mu_3\\ \mu_4 \\ 
\delta_2\\ \delta_3\\ \delta_4 \\	
\beta^{SA}_{2,0}\\	\beta^{SA}_{2,1}\\	\beta^{SA}_{2,2}\\	
\beta^{SA}_{3,-2}\\	\beta^{SA}_{3,0}\\	\beta^{SA}_{3,1}\\	
\beta^{SA}_{4,-3}\\	\beta^{SA}_{4,-2}\\	\beta^{SA}_{4,0}
\end{array}\right)\\ 
\epsilon & =\left(\begin{array}{c}	
\epsilon_{1,1} \\ \vdots \\\epsilon_{N_1,1}\\ \epsilon_{1,2} \\ \vdots \\ \epsilon_{N_2,2}\\ \epsilon_{1,3} \\ \vdots \\ \epsilon_{N_3,3}\\ \epsilon_{1,4} \\ \vdots \\ \epsilon_{N_4,4}
\end{array}\right), 
\end{align*}

with $D^d_i=\uns{D_i=d}$ and $N_t$ the number of observations at time $t$. 
If we are in a panel, each $i$ is the same across time periods. 
If we are in a repeated cross section, the $i$ index refers to different individuals.
This model is very difficult to solve by brute force, since its $X'X$ matrix is $16 \times 16$ and has no easy simplification on sight. 
Here is the $X'X$ for panel data (which is slightly simpler), with $\bar{D^d}=\frac{1}{N}\sum_{i=1}^N\uns{D_i=d}$, and $N$ the number of individuals in the panel:

\begin{align*} 
X'X & = N\left(\begin{array}{cccccccccccccccc} 
T & T\bar{D^2} & T\bar{D^3} & T\bar{D^4} & 1 & 1 & 1 & \bar{D^2} & \bar{D^2} & \bar{D^2} & \bar{D^3} & \bar{D^3} & \bar{D^3} & \bar{D^4} & \bar{D^4} & \bar{D^4}\\
T\bar{D^2} & T\bar{D^2} & 0           & 0          & \bar{D^2} & \bar{D^2} & \bar{D^2} & \bar{D^2} & \bar{D^2} & \bar{D^2} & 0         & 0         & 0 & 0 & 0 & 0 \\ 
T\bar{D^3} & 0          & T\bar{D^3}  & 0          & \bar{D^3} & \bar{D^3} & \bar{D^3} & 0         & 0         & 0         & \bar{D^3} & \bar{D^3} & \bar{D^3}   & 0 & 0 & 0\\ 
T\bar{D^4} & 0          & 0           & T\bar{D^4} & \bar{D^4} & \bar{D^4} & \bar{D^4} & 0         & 0         & 0 & 0    & 0    & 0   & \bar{D^4} & \bar{D^4} & \bar{D^4}\\ 
1 & \bar{D^2}  & \bar{D^3}   & \bar{D^4}  & 1         & 0         & 0         & \bar{D^2} & 0 & 0         & 0    & 0    & 0   & 0 & \bar{D^4} & 0 \\ 
1 & \bar{D^2}  & \bar{D^3}   & \bar{D^4}  & 0         & 1         & 0         & 0         & \bar{D^2} & 0         & 0   & \bar{D^3} & 0 & 0 & 0 & 0\\
1 & \bar{D^2}  & \bar{D^3}   & \bar{D^4}  & 0         & 0         & 1         & 0         & 0 & \bar{D^2} & 0   & 0          & \bar{D^3} & 0 & 0 & \bar{D^4}\\ 
\bar{D^2} & \bar{D^2} & 0            & 0          & \bar{D^2} & 0         & 0         & \bar{D^2} & 0         & 0         & 0    & 0    & 0   & 0 & 0 & 0 \\ 
\bar{D^2} & \bar{D^2} & 0            & 0          & 0         & \bar{D^2} & 0         & 0 & \bar{D^2} & 0         & 0    & 0    & 0   & 0 & 0 & 0\\ 
\bar{D^2} & \bar{D^2} & 0            & 0          & 0         & 0         & \bar{D^2} & 0         & 0 & \bar{D^2} & 0    & 0    & 0   & 0 & 0 & 0 \\ 
\bar{D^3} & 0         & \bar{D^3}    & 0          & 0         & 0         & 0         & 0         & 0         &  0 & \bar{D^3} & 0    & 0   & 0 & 0 & 0  \\ 
\bar{D^3} & 0         & \bar{D^3}    & 0          & 0         & \bar{D^3} & 0         & 0         & 0         &  0 & 0         & \bar{D^3} & 0   & 0 & 0 & 0   \\ 
\bar{D^3} & 0         & \bar{D^3}    & 0          & 0         & 0         & \bar{D^3} & 0         & 0         &  0 & 0         & 0         & \bar{D^3} & 0 & 0 & 0 \\ 
\bar{D^4} & 0         & 0            & \bar{D^4}  & 0         & 0         & 0         & 0         & 0         &  0 & 0         & 0         &  0        & \bar{D^4} & 0 & 0 \\ 
\bar{D^4} & 0         & 0            & \bar{D^4}  & \bar{D^4} & 0         & 0         & 0         & 0         & 0        & 0         & 0         &  0        & 0 & \bar{D^4} & 0 \\ 
\bar{D^4} & 0         & 0            & \bar{D^4}  & 0         & 0         & \bar{D^4} & 0         & 0         &  0        & 0         & 0         &  0        & 0 & 0 & \bar{D^4} 
\end{array}\right) 
\end{align*}

The epiphany comes when you are able to write this model with a separate constant, time and group dummies for each separate treated group for which we want to estimate the DID model for. 
We have 9 separate interaction parameters $\beta^{SA}_{d,\tau}$ to estimate. We are thus going to estimate $9 \times 4$ parameters total (*i.e.* run 9 separate regressions with four parameters, but all at once). 
We thus have to write a $36 \times 36$ $X'X$ matrix. 
The key is that this matrix is going to be block diagonal, with $4 \times 4$ blocks that are identical to the blocks of the $X'X$ matrix in the case of a simple OLS DID estimator with two time periods. 
Also, the parameters that are redundant in this model (*i.e.* that appear several times at different places) will be estimated in exactly the same way, which shows that the two formulations of the model ($16 \times 16$ and $36 \times 36$) are equivalent and estimate the exact same set of
16 parameters.
In order to see how this works (and to prove the result), let's write the model for $\beta^{SA}_{2,0}$. 
To be able to do that, we are going to order all the observations in each time period by the opposite of the treatment group to which they belong. 
We also denote $N_t^{d}$ the number of observations of group $D_i=d$ in period $t$, $D^d_{i,t}=\uns{D_i=d}$ and $T^{d+\tau}_{i,t}=\uns{d+\tau=t}$. 
With these notations, we have:

\begin{align*} 
\underbrace{\left(\begin{array}{c} 
Y_{1,1} \\	\vdots \\	Y_{N_1^{\infty},1} \\Y_{N_1^{\infty}+1,1} \\	\vdots \\	Y_{N_1^{\infty}+N_1^{2},1} \\ Y_{1,2} \\	\vdots \\	Y_{N_2^{\infty},2} \\Y_{N_2^{\infty}+1,2} \\	\vdots \\	Y_{N_2^{\infty}+N_2^{2},2} 
\end{array}\right)}_{Y_{2,0}} & = 
\underbrace{\left(\begin{array}{cccc} 
1 & D^2_{1,1} & T^2_{1,1} & D^2_{1,1}T^2_{1,1}\\ \vdots & \vdots & \vdots & \vdots\\
1 & D^2_{N_1^{\infty},1} & T^2_{N_1^{\infty},1} & D^2_{N_1^{\infty},1}T^2_{N_1^{\infty},1} \\ 
1 & D^2_{N_1^{\infty}+1,1} & T^2_{N_1^{\infty}+1,1} & D^2_{N_1^{\infty}+1,1}T^2_{N_1^{\infty}+1,1} \\ 
\vdots & \vdots & \vdots & \vdots\\ 
1 & D^2_{N_1^{\infty}+N_1^{2},1} & T^2_{N_1^{\infty}+N_1^{2},1} & D^2_{N_1^{\infty}+N_1^{2},1}T^2_{N_1^{\infty}+N_1^{2},1} \\ 
1 & D^2_{1,2} & T^2_{1,2} & D^2_{1,2}T^2_{1,2}\\ \vdots & \vdots & \vdots & \vdots\\ 
1 & D^2_{N_1^{\infty},2} & T^2_{N_1^{\infty},2} & D^2_{N_1^{\infty},2}T^2_{N_1^{\infty},2} \\ 
1 & D^2_{N_1^{\infty}+1,2} & T^2_{N_1^{\infty}+1,2} & D^2_{N_1^{\infty}+1,2}T^2_{N_1^{\infty}+1,2} \\ 
\vdots & \vdots & \vdots & \vdots\\ 1 & D^2_{N_1^{\infty}+N_1^{2},2} & T^2_{N_1^{\infty}+N_1^{2},2} & D^2_{N_1^{\infty}+N_1^{2},2}T^2_{N_1^{\infty}+N_1^{2},2} 
\end{array}\right)}_{X_{2,0}}
\underbrace{\left(\begin{array}{c}	
\tilde\alpha_{2,0} \\ \tilde\mu_{2,0} \\ \tilde\delta_{2,0} \\	\beta^{SA}_{2,0} \end{array}\right)}_{\Theta_{2,0}} + 
\underbrace{\left(\begin{array}{c} 
\epsilon_{1,1} \\	\vdots \\	\epsilon_{N_1^{\infty},1} \\\epsilon_{N_1^{\infty}+1,1} \\	\vdots \\	\epsilon_{N_1^{\infty}+N_1^{2},1} \\ \epsilon_{1,2} \\	\vdots \\	\epsilon_{N_2^{\infty},2} \\\epsilon_{N_2^{\infty}+1,2} \\	\vdots \\	\epsilon_{N_2^{\infty}+N_2^{2},2} 
\end{array}\right)}_{\epsilon_{2,0}}
\end{align*}

Now, we can write 9 such models, one for each $\beta^{SA}_{d,\tau}$. 
If we stack the $Y_{d,\tau}$ on top of each other, starting with $d=2$ and $\tau=0$, and we stack in the same way the $\Theta_{d,\tau}$ vectors, and, finally, we regroup all the $X_{d,\tau}$ matrices in a block diagonal matrix, we have a new model
$\tilde{Y}  = \tilde{X}\tilde{\Theta} + \tilde{\epsilon}$. 
The stacked model has $4 \times 9=36$ parameters while the original model has 16 parameters. 
For the two models to be identical, it has to be that there exists $36-16=20$ direct restrictions on the parameters of the stacked model. 
Using the fact that some parts of the data set are duplicated in teh stack model, we can determine the link between the parameters in the stacked model and the ones in the original model. 
For example, we know that $Y_{1,1}=\tilde{\alpha}_{2,0}+\epsilon_{1,1}=\tilde{\alpha}_{2,1}+\epsilon_{1,1}=\tilde{\alpha}_{2,2}+\epsilon_{1,1}=\alpha+\epsilon_{1,1}$.
As a consequence, we have $\tilde{\alpha}_{2,0}=\tilde{\alpha}_{2,1}=\tilde{\alpha}_{2,2}=\alpha$. 
Using similar sets of restrictions, we can also show that: $\tilde\delta_{2,0}=\delta_2$, $\tilde\delta_{2,1}=\delta_3$ and $\tilde\delta_{2,2}=\delta_4$; $\tilde{\mu}_{d,\tau}=\mu_d$, $\forall d,\tau$; $\tilde{\alpha}_{3,-2}=\tilde{\alpha}_{3,0}=\tilde{\alpha}_{3,1}=\alpha+\delta_2$;
$\tilde{\alpha}_{4,-3}=\tilde{\alpha}_{4,-2}=\tilde{\alpha}_{4,0}=\alpha+\delta_3$; $\tilde\delta_{3,-2}=-\delta_2$; $\tilde\delta_{3,0}=\delta_3-\delta_2$; $\tilde\delta_{3,1}=\delta_4-\delta_2$; $\tilde\delta_{4,-3}=-\delta_3$; $\tilde\delta_{4,-2}=\delta_2-\delta_3$; $\tilde\delta_{4,0}=\delta_4-\delta_3$.
We have thus shown that every single parameter in the stacked model can be derived from the parameters in the original model. What is left to check now is that the estimation of the stacked model by OLS abides by the constraints
implied by these equalities.
In order to complete the proof, we make use of the fact that [the inverse of a block diagonal matrix is the blog diagonal matrix of the inverses of each block](https://en.wikipedia.org/wiki/Block_matrix). 
Using the proof of Theorem \@ref(thm:asympnoiseDIDCross) (especially the beginning of the proof, which derives the OLS DID estimator in repeated cross sections of different sizes), we can now show that:

\begin{align*} 
\hat{\tilde{\alpha}}^{OLS}_{d,\tau} & = \bar{Y}^{\infty}_{d-1}\\
\hat{\tilde{\mu}}^{OLS}_{d,\tau} & = \bar{Y}^{d}_{d-1}-\bar{Y}^{\infty}_{d-1}\\
\hat{\tilde{\delta}}^{OLS}_{d,\tau} & =
\bar{Y}^{\infty}_{d+\tau}-\bar{Y}^{\infty}_{d-1}\\ \hat{\beta}^{SA}_{d,\tau} & =
\bar{Y}^{d}_{d+\tau}-\bar{Y}^{d}_{d-1}-(\bar{Y}^{\infty}_{d+\tau}-\bar{Y}^{\infty}_{d-1}).
\end{align*}

These results show that all the constraints on the parameters of the stacked model are verified (I leave this as an exercise). 
The last equality proves the result for the OLS DID model in repeated cross sections. 
The proof for panel data follows exactly the same lines.

Let us now turn to the First Difference estimator in panel data.
The First Difference transformation of Sun and Abraham model which uses $d-1$ as the benchmark period can be written as follows (for $\tau\neq-1$):

\begin{align*}
  Y_{i,d+\tau} - Y_{i,d-1} & = \alpha_{d,\tau}^{FD} + \beta_{d,\tau}^{FD}\uns{D_i=d} + \epsilon^{FD}_{i,d+\tau},
\end{align*}

with:

\begin{align*}
  \alpha_{d,\tau}^{FD} & = \delta_{d+\tau} - \delta_{d-1}\\
  \beta_{d,\tau}^{FD} & = \beta_{d,\tau}^{SA}\\
  \epsilon^{FD}_{i,d+\tau} & = \epsilon^{SA}_{i,d+\tau}-\epsilon^{FD}_{i,d-1}.
\end{align*}

Using the same trick as for the model in repeated cross sections, we can rewrite this model as stacked model with a block diagonal matrix of covariates.
Here is the block corresponding to the estimation of $\beta^{SA}_{2,0}$:

\begin{align*} 
\underbrace{\left(\begin{array}{c} 
Y_{1,2}-Y_{1,1}  \\	\vdots \\	Y_{N^{\infty},2}-	Y_{N^{\infty},1} \\Y_{N^{\infty}+1,2}-Y_{N^{\infty}+1,1} \\	\vdots \\	Y_{N^{\infty}+N^{2},2} -Y_{N^{\infty}+N^{2},1}
\end{array}\right)}_{\Delta Y_{2,0}} & = 
\underbrace{\left(\begin{array}{cccc} 
1 & 0 \\ 
\vdots & \vdots\\ 
1 & 0 \\ 
1 & 1 \\ 
\vdots & \vdots\\ 
1 & 1 
\end{array}\right)}_{\Delta X_{2,0}}
\underbrace{\left(\begin{array}{c}	
\alpha^{FD}_{2,0} \\ 	\beta^{FD}_{2,0} \end{array}\right)}_{\Theta^{FD}_{2,0}} + 
\underbrace{\left(\begin{array}{c} 
\epsilon^{FD}_{1,2} \\	\vdots \\	\epsilon^{FD}_{N^{\infty},2} \\\epsilon^{FD}_{N^{\infty}+1,2} \\	\vdots \\	\epsilon^{FD}_{N^{\infty}+N^{2},2} 
\end{array}\right)}_{\epsilon^{FD}_{2,0}}
\end{align*}

Stacking all the vectors of outcomes, the vector of coefficients and the vector of residuals on top of each other, and organizing the matrices of covariates in a block diagonal matrix, we obtain the stacked Sun and Abraham model in first differences: $\Delta Y = \Delta X\Theta^{FD} + \epsilon^{FD}$.
Using the fact that [the inverse of a block diagonal matrix is the blog diagonal matrix of the inverses of each block](https://en.wikipedia.org/wiki/Block_matrix) and the proof of Lemma \@ref(lem:WWOLS), we can show that $\hat\beta^{FD}_{d,\tau}$ is the with/without estimator applied to $Y_{i,d+\tau} - Y_{i,d-1}$.
The result follows.

Let us now study the Within estimator of Sun and Abraham model in panel data.
The within mean of Sun and Abraham model depends on the group the observation belongs to.
For $i$ such that $D_i=d$, we have:

\begin{align*}
  \underbrace{\frac{1}{T}\sum_{t=1}^TY_{i,t}}_{\bar{Y}_{i,.}} = \underbrace{\frac{1}{T}\sum_{t=1}^T\delta_{t}}_{\bar{\delta}}+ \underbrace{\frac{1}{T}\sum_{\tau\neq-1}^T\beta_{d,\tau}^{SA}}_{\bar{\beta}_d} \uns{D_i=d}+\underbrace{\frac{1}{T}\sum_{t=1}^T\epsilon_{i,t}}_{\bar{\epsilon}_{i,.}}.
\end{align*}

As a consequence, for $i$ such that $D_i=d$ or $D_i=\infty$, we can write the within transformation of Sun and Abraham model as follows:

\begin{align*}
  Y_{i,d+\tau}-\bar{Y}_{i,.} & = \underbrace{\delta_{d-1}-\bar{\delta}}_{\alpha_d^{FE}}+\underbrace{(\delta_{d+\tau}-\delta_{d-1})}_{\delta_{d+\tau}^{FE}}\uns{T_i=d+\tau}\underbrace{-\bar{\beta}_d}_{\mu_d^{FE}}\uns{D_i=d} +\beta_{d,\tau}^{SA}\uns{D_i=d}\uns{T_i=d+\tau}+\epsilon_{i,t}-\bar{\epsilon}_{i,.}.
\end{align*}

The within transformation of Sun and Abraham model is thus equivalent to the OLS DID model applied to the within-transformed outcomes $Y_{i,d+\tau}-\bar{Y}_{i,.}$.
Building a stacked model of the within transformed Sun and Abraham model and using the fact that [the inverse of a block diagonal matrix is the blog diagonal matrix of the inverses of each block](https://en.wikipedia.org/wiki/Block_matrix) along with Theorem \@ref(thm:EstimDID) proves that:

\begin{align*}
\hat\beta_{d,\tau}^{SA} & = \frac{\sum_{i=1}^{N}(Y_{i,d+\tau}-\bar{Y}_{i,.}-(Y_{i,d-1}-\bar{Y}_{i,.}))\uns{D_i=d}}{\sum_{i=1}^{N}\uns{D_i=d}} \\
                            & \phantom{=} - \frac{\sum_{i=1}^{N}(Y_{i,d+\tau}-\bar{Y}_{i,.}-(Y_{i,d-1}-\bar{Y}_{i,.}))\uns{D_i=\infty}}{\sum_{i=1}^{N}\uns{D_i=\infty}}\\
                            & = \frac{\sum_{i=1}^{N}(Y_{i,d+\tau}-Y_{i,d-1})\uns{D_i=d}}{\sum_{i=1}^{N}\uns{D_i=d}} \\
                            & \phantom{=} - \frac{\sum_{i=1}^{N}(Y_{i,d+\tau}-Y_{i,d-1})\uns{D_i=\infty}}{\sum_{i=1}^{N}\uns{D_i=\infty}},
\end{align*}

which proves the result.

Let us finally look at the Least Squares Dummy Variables estimator.
Let's denote $X_{\mu}$ the matrix of individual dummies in the LSDV estimator.
We are going to apply Theorem \@ref(thm:FWL), *i.e.* Frish-Waugh-Lovell Theorem, partialling out these individual dummies from the list of regressors.
First, we have $(X'_{\mu}X_{\mu})^{-1}=\frac{1}{T}I_N$ where $I_N$ is the identity matrix of dimension $N$ and $T$ is the total number of time periods in the panel.
Second, we have that $M_{\mu}Y=X_{\mu}(X'_{\mu}X_{\mu})^{-1}X'_{\mu}Y=\left(\dots,Y_{i,t}-\bar{Y}_{i,.},\dots\right)$.
For the time fixed effects, we have $M_{\mu}X_{-\mu,T}$ a matrix with $1-\frac{1}{T}$ where $T_{i,t}=1$ and $-\frac{1}{T}$ otherwise.
For the interactive treatment dummies, we have $M_{\mu}X_{-\mu,DT}$ a matrix with $D^d_i(1-\frac{1}{T})$ where $D^d_i$ appeared in the original $X_{-\mu,DT}$ matrix (the last 9 columns of the $X$ matrix) and $-\frac{D^d_i}{T}$ otherwise.
As a consequence of Theorem \@ref(thm:FWL), we can rewrite the LSDV model as follows:

\begin{align*}
  Y_{i,t} - \bar{Y}_{i,.} & = \delta_t-\bar\delta-\sum_d\bar\beta^{SA}_d\uns{D_i=d}+\sum_d\sum_{\tau\neq-1}\beta^{SA}_{d,\tau}\uns{D_i=d}\uns{t=d+\tau}+\epsilon^{LSDV}_{i,t} - \bar{\epsilon}^{LSDV}_{i,.}.
\end{align*}

This is the same formula as the one we have uncovered in the within transformation we have studied just above.
Using the same approach proves the result.

### Proof of Theorem \@ref(thm:asympnoiseSACross) {#proofasympnoiseSACross}

Using the beginning of the proof of Lemma \@ref(lem:asympOLS), we know that: $\sqrt{N}(\hat{\tilde\Theta}_{OLS}-\tilde\Theta)=N(\tilde{X}'\tilde{X})^{-1}\frac{\sqrt{N}}{N}\tilde{X}'\tilde{\epsilon}$.
Using Slutsky's Theorem, we know that we can study both terms separately (see the same proof of Lemma \@ref(lem:asympOLS)). 
$N(\tilde{X}'\tilde{X})^{-1}$ can be derived rather directly from the fact that Sun and Abraham model can be written as a block diagonal matrix, as shown in the proof of Theorem \@ref(thm:EquivDIDSAsamp). 
The most difficult part is going to be to derive the distribution of $\frac{\sqrt{N}}{N}\tilde{X}'\tilde{\epsilon}$.

Let us start with $N(\tilde{X}'\tilde{X})^{-1}$.
Let us define $N_{t,d}$ the number of observations observed in group $d$ at period $t$. 
We also define $N^B_{d,\tau}=N_{d-1,\infty}+N_{d-1,d}$ the number of observations used to estimate $\hat{\beta}^{SA}_{d,\tau}$ that are observed in the reference (or before) period and $N^A_{d,\tau}=N_{d+\tau,\infty}+N_{d+\tau,d}$ the number of observations used to estimate $\hat{\beta}^{SA}_{d,\tau}$ that are observed in the after period. 
We also define $N^{SA}_{d,\tau}=N^A_{d,\tau}+N^B_{d,\tau}$, the number of observations used to estimate $\hat{\beta}^{SA}_{d,\tau}$. 
We also define $\bar{T}_A^{d,\tau}=\frac{N^A_{d,\tau}}{N^{SA}_{d,\tau}}$, $k^{d,\tau}=\frac{N^B_{d,\tau}}{N^{A}_{d,\tau}}=\frac{1-\bar{T}_A^{d,\tau}}{\bar{T}_A^{d,\tau}}$. 
We let $\bar{D}_A^{d,\tau}$ and $\bar{D}_B^{d,\tau}$ denote the proportion of treated observations in the after and before periods used to estimate $\hat{\beta}^{SA}_{d,\tau}$. 
We also define $\bar{P}^{d,\tau}=\frac{N^{SA}_{d,\tau}}{N}$ the proportion of observations used to estimate $\hat{\beta}^{SA}_{d,\tau}$. 
We also have: $\text{plim}\bar{P}^{d,\tau}=p^{d,\tau}$, $\text{plim}\bar{D}_A^{d,\tau}=\text{plim}\bar{D}_B^{d,\tau}=p^{d,\tau}_D$ and $\text{plim}\bar{T}_A^{d,\tau}=p^{d,\tau}_A$. $p^{d,\tau}=\Pr(D^{d,\tau}_i=1)$, with $D^{d,\tau}_i=\uns{(D_i=d\lor D_i=\infty)\land(T_i=d-1\lor T_i=d+\tau)}$ a dummy indicating that a unit in the population belongs to the set of units used to identify $\beta^{SA}_{d,\tau}$. $p^{d,\tau}_D=\Pr(D_i=d|D^{d,\tau}_i=1)$ is the proportion of treated units among the set of units used to identify $\beta^{SA}_{d,\tau}$. 
$p^{d,\tau}_A=\Pr(T_i=d+\tau|D^{d,\tau}_i=1)$ is the proportion of units belonging to the after period among the set of units used to identify $\beta^{SA}_{d,\tau}$. 
Finally, let $(X'X)^{-1}_{d,\tau}$ denote the block of the matrix $(\tilde{X}'\tilde{X})^{-1}$ which is used to estimate $\hat{\beta}^{SA}_{d,\tau}$. 
With all these definitions, we can now follow the proof of Theorem \@ref(thm:asympnoiseDIDCross) in order to derive the following result: 

\begin{align*}
\sigma_{\tilde{X}\tilde{X}^{-1}}^{d,\tau} &= \text{plim}N(X'X)^{-1}_{d,\tau} = \frac{1}{p^{d,\tau}(1-p^{d,\tau}_A)(1-p^{d,\tau}_D)}
\left(\begin{array}{cccc}
1 & -1 & -1 & 1\\
-1 & \frac{1}{p^{d,\tau}_D} & 1 & -\frac{1}{p^{d,\tau}_D} \\
-1 & 1 & \frac{1}{p^{d,\tau}_A} & -\frac{1}{p^{d,\tau}_A} \\
1 & -\frac{1}{p^{d,\tau}_D} & -\frac{1}{p^{d,\tau}_A}  & \frac{1}{p^{d,\tau}_Dp^{d,\tau}_A}
\end{array}\right)
\end{align*}

Using the fact that [the inverse of a block diagonal matrix is the blog diagonal matrix of the inverses of each block](https://en.wikipedia.org/wiki/Block_matrix), we now know
$\text{plim}N(\tilde{X}'\tilde{X})^{-1}=\sigma_{\tilde{X}\tilde{X}}^{-1}$ is block diagonal matrix with blocks equal to $\sigma_{\tilde{X}\tilde{X}^{-1}}^{d,\tau}$.

Let us now turn to $\frac{\sqrt{N}}{N}\tilde{X}'\tilde{\epsilon}$. 
In order to derive its distribution, we have to write Sun and Abraham model in a repeated cross section with the observations grouped by blocks corresponding to the parameters they help to estimate. 
This model can be written as:

\begin{align*}
  Y_{j}D^{d,\tau}_j &  = \tilde\alpha^{d,\tau}D^{d,\tau}_j + \tilde\mu_{d,\tau}\uns{D_{j}=d}D^{d,\tau}_j + \tilde\delta_{d,\tau}\uns{T_j=d+\tau}D^{d,\tau}_j \\
                    & \phantom{=}  +  \beta_{d,\tau}^{SA}\uns{D_{i}=d}\uns{T_j=d+\tau}D^{d,\tau}_j  + \tilde\epsilon_{j}D^{d,\tau}_j,
\end{align*}

with:

\begin{align*}
\tilde\epsilon_{j} & = Y_{j}-\left(\esp{Y^0_{j}|D_j=\infty,T_j=d-1}\right.\\
                          & \phantom{=Y_{j}-\left(\right.}+\uns{D_j=d}(\esp{Y^0_{j}|D_j=d,T_j=d-1}-\esp{Y^0_{j}|D_j=\infty,T_j=d-1})
                          & \phantom{=Y_{j}-\left(\right.}+\uns{T_j=d+\tau}(\esp{Y^0_{j}|D_j=\infty,T_j=d+\tau}-\esp{Y^0_{j}|D_j=\infty,T_j=d-1})\\
                          & \phantom{=Y_{j}-\left(\right.}+\uns{D_{j}=d}\uns{T_j=d+\tau}(\esp{Y^1_{j}|D_j=d,T_j=d+\tau}-\esp{Y^0_{j}|D_j=d,T_j=d-1}\\
                          & \phantom{=Y_{j}-\left(\right.+\uns{D_{j}=d}\uns{T_j=d+\tau}}\left.-(\esp{Y^0_{j}|D_j=\infty,T_j=d+\tau}-\esp{Y^0_{j}|D_j=\infty,T_j=d-1}))\right).
\end{align*}

It is pretty straightforward to prove that $\esp{\tilde\epsilon_{j}D^{d,\tau}_j}=0$.
For that, note that $D^{d,\tau}_j=f(D_j,T_j)$ so that conditioning on $D^{d,\tau}_j$ is irrelevant when also conditioning on $(D_j,T_j)$.
Then, check that $\esp{\tilde\epsilon_{j}D^{d,\tau}_j\uns{D_{j}=d}\uns{T_j=d+\tau}}=0$.
The same thing holds for $\esp{\tilde\epsilon_{j}D^{d,\tau}_j\uns{T_j=d+\tau}}=0$ and for $\esp{\tilde\epsilon_{j}D^{d,\tau}_j\uns{D_{j}=d}}=0$, which proves the result.

It can also be shown that $\esp{\tilde\epsilon_{j}D^{d,\tau}_jD^{d',\tau'}_j}=0$, with either $j\neq j'$ or $\tau\neq \tau'$ or both.
If it is the case that $D^{d,\tau}_j\Ind D^{d',\tau'}_j$, then the term is zero.
If $D^{d,\tau}_j$ and $D^{d',\tau'}_j$ are not independent, by definition of $D^{d,\tau}_j$, $\esp{\tilde\epsilon_{j}D^{d,\tau}_jD^{d',\tau'}_j}$ can only involve the following terms: $\esp{\tilde\epsilon_{j}|D_j=d,T_j=d+\tau}$, $\esp{\tilde\epsilon_{j}|D_j=d,T_j=d-1}$, $\esp{\tilde\epsilon_{j}|D_j=\infty,T_j=d+\tau}$ and $\esp{\tilde\epsilon_{j}|D_j=\infty,T_j=d-1}$, and all of these terms are equal to zero.

Using the vector version of the Central Limit Theorem that we have already used in the proof of Theorem \@ref(thm:asympnoiseDIDCross), we thus have that $\frac{\sqrt{N}}{N}\tilde{X}'\tilde{\epsilon}\sim\mathcal{N}(\mathbf{0},\mathbf{V_{\tilde{x}\tilde{\epsilon}}})$.
Using the Delta Method, we have that  $\sqrt{N}(\hat{\Theta}_{OLS}-\Theta)\stackrel{d}{\rightarrow}\mathcal{N}\left(\mathbf{0},\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}\right)$.
In order to prove the result, we simply need to derive the fourth term on the diagonal of each $4\times 4$ block of $\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}$.
Since $\sigma_{\tilde{X}\tilde{X}}^{-1}$ is block diagonal, the $4\times 4$ blocks of $\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}$ are equal to $\sigma_{\tilde{X}\tilde{X}^{-1}}^{d,\tau}\mathbf{V}^{d,\tau}_{\mathbf{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}^{-1}}^{d,\tau}$, with (following the proof of Theorem \@ref(thm:asympnoiseDIDCross)):

\begin{align*}
  \mathbf{V}^{d,\tau}_{\mathbf{\tilde{x}\tilde{\epsilon}}} & =
                                        \esp{\epsilon_j^2D^{d,\tau}_j\left(\begin{array}{cccc}
                                              1 & D^d_j &	T^{d,\tau}_j & D^d_jT^{d,\tau}_j \\
                                              D^d_j & D^d_j &	D^d_jT^{d,\tau}_j & D^d_jT^{d,\tau}_j \\
                                              T^{d,\tau}_j & D^d_jT^{d,\tau}_j &	T^{d,\tau}_j & D^d_jT^{d,\tau}_j \\
                                              D^d_jT^{d,\tau}_j & D^d_jT^{d,\tau}_j &	D^d_jT^{d,\tau}_j & D^d_jT^{d,\tau}_j
                                            \end{array}\right)},
\end{align*}

with $D^d_j=\uns{D_{j}=d}$ and $T_j^{d,\tau}=\uns{T_j=d+\tau}D^{d,\tau}_j$.
Following the proof of Theorem \@ref(thm:asympnoiseDIDCross) proves the result.

### Proof of Theorem \@ref(thm:asympnoiseSATTCross) {#proofasympnoiseSATTCross}

The key to the proof relies on the covariance terms.
The covariance terms come from the off-$4\times 4$-block-diagonal elements of the $\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}$ matrix.
They are due to the fact that the same data are used repeatedly to estimate the $\beta^{SA}_{d,\tau}$ parameters.
For example, the observations from the never treated group are used as benchmarks for the estimation of $\beta^{SA}_{2,0}$, $\beta^{SA}_{2,1}$ and $\beta^{SA}_{2,2}$.
The same observations are used as post-treatment observations for the estimation of $\beta^{SA}_{2,0}$, $\beta^{SA}_{3,-2}$ and $\beta^{SA}_{4,-3}$.

In order to rigorously derive these covariance terms, we need to derive the off-$4\times 4$-block-diagonal elements of the $\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}$ matrix in the proof of Theorem \@ref(thm:asympnoiseSACross).
For two sets of observations used to estimate $\beta^{SA}_{d,\tau}$ and $\beta^{SA}_{d',\tau'}$, $d\neq d'$ or $\tau\neq\tau'$, we only need the last line of the off-$4\times 4$-block-diagonal covariance matrix of $\sigma_{\tilde{X}\tilde{X}}^{-1}\mathbf{V_{\tilde{x}\tilde{\epsilon}}}\sigma_{\tilde{X}\tilde{X}}^{-1}$.
Indeed, using results in the proof of Theorem \@ref(thm:asympnoiseSACross), we can show that:

\begin{align*}
  \text{Cov}(\hat{\beta}^{SA}_{d,\tau},\hat{\beta}^{SA}_{d',\tau'}) & = \frac{1}{p^{d,\tau}p^{d',\tau'}(1-p_A^{d,\tau})(1-p_A^{d',\tau'})(1-p_D^{d,\tau})(1-p_D^{d',\tau'})} \\
                & \phantom{=}  \left(\mathbf{A}_4-\frac{1}{p_D^{d,\tau}}\mathbf{B}_4-\frac{1}{p_A^{d,\tau}}\mathbf{C}_4+\frac{1}{p_A^{d,\tau}p_D^{d,\tau}}\mathbf{D}_4\right),
\end{align*}

with:

\begin{align*}
  \mathbf{A}_4 & = \esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}} -\frac{1}{p_D^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D_j^{d,\tau}} -\frac{1}{p^{d',\tau'}_A}\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D_j^{d,\tau}} \\
                & \phantom{=} + \frac{1}{p_D^{d',\tau'}p_A^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jT^{d',\tau'}_jD_j^{d',\tau'}D_j^{d,\tau}}\\
  \mathbf{B}_4 & = \esp{\epsilon_j^2D_j^{d',\tau'}D^{d}_jD_j^{d,\tau}} -\frac{1}{p_D^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D^{d}_jD_j^{d,\tau}} -\frac{1}{p^{d',\tau'}_A}\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D^{d}_jD_j^{d,\tau}} \\
                & \phantom{=} + \frac{1}{p_D^{d',\tau'}p_A^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jT^{d',\tau'}_jD_j^{d',\tau'}D^{d}_jD_j^{d,\tau}}\\
  \mathbf{C}_4 & = \esp{\epsilon_j^2D_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}} -\frac{1}{p_D^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}} -\frac{1}{p^{d',\tau'}_A}\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}} \\
                & \phantom{=} + \frac{1}{p_D^{d',\tau'}p_A^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jT^{d',\tau'}_jD_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}}\\
\mathbf{D}_4 & = \esp{\epsilon_j^2D_j^{d',\tau'}D^{d}_jT^{d,\tau}_jD_j^{d,\tau}} -\frac{1}{p_D^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D^{d}_jT^{d,\tau}_jD_j^{d,\tau}} -\frac{1}{p^{d',\tau'}_A}\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D^{d}_jT^{d,\tau}_jD_j^{d,\tau}} \\
                & \phantom{=} + \frac{1}{p_D^{d',\tau'}p_A^{d',\tau'}}\esp{\epsilon_j^2D^{d'}_jT^{d',\tau'}_jD_j^{d',\tau'}D^{d}_jT^{d,\tau}_jD_j^{d,\tau}}
\end{align*}

Let us start with $\mathbf{A}_4$'s first term, $\esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}}$.
Note first that if $d=d'$, we have to have $\tau\neq\tau'$, otherwise the term would be on the diagonal.
As a consequence, with $d=d'$, we can have only two configurations for which $D_j^{d',\tau'}D_j^{d,\tau}=1$, and they both correspond to a baseline observation ($T_j=d-1$) either for the control group ($D_j=\infty$) or for the treated group ($D_j=d$).
In that case, we thus have:

\begin{align*}
\esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}} & = \left(\var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})\right.\\
                                            & \phantom{=}\left.+\var{Y^0_{i,d-1}|D_i=d}p_D^{d,\tau,d',\tau'}\right)p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'},
\end{align*}

with $p_D^{d,\tau,d',\tau'}$ the proportion of treated individuals in the group such as $D_j^{d',\tau'}D_j^{d,\tau}=1$ and $p_{d-1}^{d,\tau,d',\tau'}$ is the proportion of observations observed in period $d-1$ among the observations such as $D_j^{d',\tau'}D_j^{d,\tau}=1$ and $p^{d,\tau,d',\tau'}$ the proportion of observations such as $D_j^{d',\tau'}D_j^{d,\tau}=1$.

When $d\neq d'$, we have three possible cases: $d-1=d'+\tau'$, $d'-1=d+\tau$ or $d'+\tau'=d+\tau$.
Because the treated groups are different in that case, the only possible correspondence in these cases is due to the control group, with the After period for one treated group being the Before period for another treated group or the After periods being the same for both groups.
If $d-1=d'+\tau'$, we have:

\begin{align*}
  \esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}} & = \var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'},
\end{align*}

where $p_{d-1}^{d,\tau,d',\tau'}$ is the proportion of observations observed in period $d-1$ among the observations such as $D_j^{d',\tau'}D_j^{d,\tau}=1$.

If $d'-1=d+\tau$, we have:

\begin{align*}
  \esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}} & = \var{Y^0_{i,d'-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d'-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

Finally, if $d'+\tau'=d+\tau$, we have:

\begin{align*}
  \esp{\epsilon_j^2D_j^{d',\tau'}D_j^{d,\tau}} & = \var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d+\tau}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

Let us now look at the next term: $\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D_j^{d,\tau}}$.
Here, there is only one case that yields a non zero term, when $d=d'$ (all the other configurations involve only the untreated group and thus have $D^{d'}_j=0$).
In that case, we have:

\begin{align*}
  \esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D_j^{d,\tau}} & = \var{Y^0_{i,d'-1}|D_i=d'}p_D^{d,\tau,d',\tau'}p_{d'-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

Let us now look at the next term: $\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D_j^{d,\tau}}$.
Here, there are two cases that yield a non zero term, when $d-1=d'+\tau'$ and when $d'+\tau'=d+\tau$ (all the other configurations involve only the Before period and thus have $T^{d',\tau'}_j=0$).
In both case, we have:

\begin{align*}
  \esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D_j^{d,\tau}} & = \var{Y^0_{i,d'+\tau'}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d'+\tau'}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

Let us now look at the next term: $\esp{\epsilon_j^2D^{d'}_jT^{d',\tau'}_jD_j^{d',\tau'}D_j^{d,\tau}}$.
This term is equal to zero since there is no treated observation observed in a post-treatment period such that $D_j^{d',\tau'}D_j^{d,\tau}=1$.

Let us now move on to $\mathbf{B}_4$.
For $\esp{\epsilon_j^2D_j^{d',\tau'}D^{d}_jD_j^{d,\tau}}$ to be non zero, we have to have that $d=d'$ (otherwise, $D_j^d=0$).
The only corresponding nonzero case corresponds to a baseline observation for the treated group:

\begin{align*}
  \esp{\epsilon_j^2D_j^{d',\tau'}D^{d}_jD_j^{d,\tau}} & = \var{Y^0_{i,d-1}|D_i=d}p_D^{d,\tau,d',\tau'}p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

The next term ($\esp{\epsilon_j^2D^{d'}_jD_j^{d',\tau'}D^{d}_jD_j^{d,\tau}}$) is the same since, with $d=d'$, $D_j^d=D_j^{d'}$.
The last two terms of $\mathbf{B}_4$ are null everywhere.
This is because it can only be that $d=d'$ (since $D_j^d=1$) and it cannot be a baseline observation (since $T^{d,\tau'}_j=1$).
Since treated observations appear only once for each $d$, $\tau\neq\tau'\Rightarrow\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}D^{d}_jD_j^{d,\tau}}=0$.

Let us now move on to $\mathbf{C}_4$.
For the first term $\esp{\epsilon_j^2D_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}}$, we cannot have nonzero terms when $d=d'$, since this case involves only baseline period variances and this contradicts $T^{d,\tau}_j=1$, and thus the term is null in that case.
The only possible nonzero cases involve $d'-1=d+\tau$ or $d'+\tau'=d+\tau$.
In that case, we have:

\begin{align*}
  \esp{\epsilon_j^2D_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}} & = \var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d+\tau}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

The next term in $\mathbf{C}_4$ is zero everywhere since it involves the same term as above plus the additional requirement that $D^{d'}_j=1$.
Since this entails that observations have to belong to a treatment group, and the previous term only includes terms from the control group, this term has to be zero everywhere.

The term $\esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}}$ is non zero only when $d'+\tau'=d+\tau$ (it is the same as the first term in $\mathbf{C}_4$ with the added constraint that $T^{d',\tau'}_j=1$).
We thus have:
\begin{align*}
  \esp{\epsilon_j^2T^{d',\tau'}_jD_j^{d',\tau'}T^{d,\tau}_jD_j^{d,\tau}} & = \var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d+\tau}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}.
\end{align*}

The last term in $\mathbf{C}_4$ everywhere since it is a subset of the second term, which is already zero.

Finally, all the terms in $\mathbf{D}_4$ are equal to zero.
This is because $T^{d,\tau}_jD^{d}_j=1$ implies that we cannot have $d=d'$ (because the only nonzero terms would then be the ones in the baseline period, which contradicts the fact that $T^{d,\tau}_j=1$).
The remaining potential nonzero configurations only concern the control group, which runs counter $D^{d}_j=1$.
Hence the result.

Collecting terms, we now have, when $d=d'$:

\begin{align*}
  \mathbf{A}_4 & = \var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}\\
             & \phantom{=}+\var{Y^0_{i,d-1}|D_i=d}p_D^{d,\tau,d',\tau'}p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}(1-\frac{1}{p_D^{d',\tau'}})\\
  \mathbf{B}_4 & = \var{Y^0_{i,d-1}|D_i=d}p_D^{d,\tau,d',\tau'}p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}(1-\frac{1}{p_D^{d',\tau'}})\\
  \mathbf{C}_4 & = 0 \\
\mathbf{D}_4 & = 0,
\end{align*}

and thus:

\begin{align*}
  \text{Cov}(\hat{\beta}^{SA}_{d,\tau},\hat{\beta}^{SA}_{d',\tau'}) & = \frac{p^{d,\tau,d',\tau'}p_{d-1}^{d,\tau,d',\tau'}}{p^{d,\tau}p^{d',\tau'}} \left(\frac{\var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})}{(1-p_A^{d,\tau})(1-p_A^{d',\tau'})(1-p_D^{d,\tau})(1-p_D^{d',\tau'})} \right.\\
                & \phantom{=}\left.+\frac{\var{Y^0_{i,d-1}|D_i=d}p_D^{d,\tau,d',\tau'}}{(1-p_A^{d,\tau})(1-p_A^{d',\tau'})p_D^{d,\tau}p_D^{d',\tau'}}\right).
\end{align*}

Alternatively, when $d+\tau=d'+\tau'$, we have:

\begin{align*}
  \mathbf{A}_4 & = \var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d+\tau}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}(1-\frac{1}{p^{d',\tau'}_A}) \\
  \mathbf{B}_4 & = 0\\
  \mathbf{C}_4 & = \var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d+\tau}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}(1-\frac{1}{p^{d',\tau'}_A})\\
\mathbf{D}_4 & = 0
\end{align*}

and thus:

\begin{align*}
  \text{Cov}(\hat{\beta}^{SA}_{d,\tau},\hat{\beta}^{SA}_{d',\tau'}) & = \frac{p^{d,\tau,d',\tau'}p_{d+\tau}^{d,\tau,d',\tau'}\var{Y^0_{i,d+\tau}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})}{p^{d,\tau}p^{d',\tau'}p_A^{d,\tau}p_A^{d',\tau'}(1-p_D^{d,\tau})(1-p_D^{d',\tau'})}
\end{align*}

Finally, when $d-1=d'+\tau'$, we have:

\begin{align*}
  \mathbf{A}_4 & = \var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'}(1-\frac{1}{p^{d',\tau'}_A})\\
  \mathbf{B}_4 & = 0\\
  \mathbf{C}_4 & = 0\\
\mathbf{D}_4 & = 0
\end{align*}

and thus:

\begin{align*}
  \text{Cov}(\hat{\beta}^{SA}_{d,\tau},\hat{\beta}^{SA}_{d',\tau'}) & = -\frac{p^{d,\tau,d',\tau'}p_{d-1}^{d,\tau,d',\tau'}\var{Y^0_{i,d-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})}{p^{d,\tau}p^{d',\tau'}(1-p_A^{d,\tau})p_A^{d',\tau'}(1-p_D^{d,\tau})(1-p_D^{d',\tau'})}.
\end{align*}

And when $d'-1=d+\tau$, we have:

\begin{align*}
  \mathbf{A}_4 & = \var{Y^0_{i,d'-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d'-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'} \\
  \mathbf{B}_4 & = 0\\
  \mathbf{C}_4 & = \var{Y^0_{i,d'-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})p_{d'-1}^{d,\tau,d',\tau'}p^{d,\tau,d',\tau'} \\
\mathbf{D}_4 & = 0
\end{align*}

and thus:

\begin{align*}
  \text{Cov}(\hat{\beta}^{SA}_{d,\tau},\hat{\beta}^{SA}_{d',\tau'}) & = -\frac{p^{d,\tau,d',\tau'}p_{d'-1}^{d,\tau,d',\tau'}\var{Y^0_{i,d'-1}|D_i=\infty}(1-p_D^{d,\tau,d',\tau'})}{p^{d,\tau}p^{d',\tau'}p_A^{d,\tau}(1-p_A^{d',\tau'})(1-p_D^{d,\tau})(1-p_D^{d',\tau'})}
\end{align*}

This proves the result.

### Proof of Theorem \@ref(thm:asympnoiseSAPanel) {#proofasympnoiseSAPanel}

The proof follows closely that of Theorem \@ref(thm:asympnoiseSACross), except that our stacked model is $\Delta Y = \Delta X\Theta^{FD} + \epsilon^{FD}$, as introduced in the proof of \@ref(thm:EquivDIDSAsamp).
Using the beginning of the proof of Lemma \@ref(lem:asympOLS), we know that: $\sqrt{N}(\hat{\Theta}^{FD}-\Theta^{FD})=N(\Delta X'\Delta X)^{-1}\frac{\sqrt{N}}{N}\Delta X'\epsilon^{FD}$.
Using Slutsky's Theorem, we know that we can study both terms separately (see the same proof of Lemma \@ref(lem:asympOLS)). 

Let us start with $N(\Delta X'\Delta X)^{-1}$.
Let's denote $N_{d,\infty}$ the number of observations that are such that $D_i=d$ or $D_i=\infty$ and $p^{d,\infty}=\text{plim}\frac{N_{d,\infty}}{N}$.
Let's also denote $p^{d,\infty}_D=\Pr(D_i=d|D_i=d\cup D_i=\infty)$.
Using the same reasoning as in the proof of Theorem \@ref(thm:asympnoiseSACross), and using the proof of Theorem \@ref(thm:asympnoiseWW), we can show that:

\begin{align*}
\sigma_{\Delta X \Delta X^{-1}}^{d,\tau} &= \text{plim}N(\Delta X'\Delta X)^{-1}_{d,\tau} = \frac{1}{p^{d,\infty}p^{d,\infty}_D(1-p^{d,\infty}_D)}
\left(\begin{array}{cc}
p^{d,\infty}_D & -p^{d,\infty}_D\\
-p^{d,\infty}_D &  1
\end{array}\right)
\end{align*}

with $N(\Delta X'\Delta X)^{-1}_{d,\tau}$ the block of the $N(\Delta X'\Delta X)^{-1}$ matrix that is related to the estimation of $\hat{\beta}^{SA}_{d,\tau}$ and using the fact that [the inverse of a block diagonal matrix is the blog diagonal matrix of the inverses of each block](https://en.wikipedia.org/wiki/Block_matrix).
The proof then follows the line of the proof of Theorem \@ref(thm:asympnoiseWW), replacing $Y_{i}$ by $Y_{i,d+\tau}-Y_{i,d-1}$.
This proves the result.

### Proof of Theorem \@ref(thm:asympnoiseSATTPanel) {#proofasympnoiseSATTPanel}

The key to the proof lies in the covariance terms.
They in turn depend on the product of the following matrix: $\sigma_{\Delta{X}\Delta{X}^{-1}}^{d,\tau,d',\tau'}\mathbf{V}^{d,\tau,d',\tau'}_{\mathbf{\Delta{x}\Delta{\epsilon}}}\sigma_{\Delta{X}\Delta{X}^{-1}}^{d,\tau,d',\tau'}$, where:

\begin{align*}
  \mathbf{V}^{d,\tau,d',\tau'}_{\mathbf{\Delta{x}\Delta{\epsilon}}} & =
                                        \esp{\Delta\epsilon_j^2\left(\begin{array}{cccc}
                                              D^{d,\tau}_j & D^d_jD^{d,\tau}_j &	D^{d,\tau}_jD^{d',\tau'}_j & D^{d'}_jD^{d,\tau}_jD^{d',\tau'}_j \\
                                              D^d_jD^{d,\tau}_j & D^d_jD^{d,\tau}_j &	D^d_jD^{d,\tau}_jD^{d',\tau'}_j & D^{d'}_jD^d_jD^{d,\tau}_jD^{d',\tau'}_j \\
                                              D^{d,\tau}_jD^{d',\tau'}_j  & D^d_jD^{d,\tau}_jD^{d',\tau'}_j  &	D^{d',\tau'}_j & D^{d'}_jD^{d',\tau'}_j \\
                                              D^{d'}_jD^{d,\tau}_jD^{d',\tau'}_j & D^{d'}_jD^d_jD^{d,\tau}_jD^{d',\tau'}_j &	D^{d'}_jD^{d',\tau'}_j & D^{d'}_jD^{d',\tau'}_j
                                            \end{array}\right)},
\end{align*}

and $\mathbf{V}^{d,\tau,d',\tau'}_{\mathbf{\Delta{x}\Delta{\epsilon}}}$ is the part of the $\mathbf{V}_{\mathbf{\Delta{x}\Delta{\epsilon}}}$ matrix that relates to the estimators of $\beta^{SA}_{d,\tau}$ and $\beta^{SA}_{d',\tau'}$.
We also have that $\sigma_{\Delta{X}\Delta{X}^{-1}}^{d,\tau,d',\tau'}$ is the blocks of the matrix $\sigma_{\Delta{X}\Delta{X}^{-1}}$ corresponding to the same estimation, with blocks formed by $\sigma_{\Delta X \Delta X^{-1}}^{d,\tau}$ and $\sigma_{\Delta X \Delta X^{-1}}^{d',\tau'}$.

## Proofs of results in Chapter \@ref(OM)

### Proof of Theorem \@ref(thm:AsympWWOLS10) {#proofAsympWWOLS10}

One way to obtain the result is to apply Theorem 7.2 in [Imbens and Rubin (2015)](https://www.cambridge.org/core/books/causal-inference-for-statistics-social-and-biomedical-sciences/71126BE90C58F1A431FE9B2DD07938AB).
A more constructive proof follows similar lines, but differs somehow at critical points.
We know that $\hat\Delta^Y_{WWOLSX}=\hat\delta^{OLS}$, where:

\begin{align*}
(\hat\alpha_1,\hat\alpha_0,\hat\beta_1,\hat\beta_0,\hat\delta^{OLS}) & = \arg\min_{\alpha_1,\alpha_0,\beta_1,\beta_0,\delta} \frac{1}{N}\sum_{i=1}^N\left(Y_i-\alpha_0 - \beta_0'X_i - (\beta_1-\beta_0)'\left(X_i-\esp{X_i|D_i=1}\right)D_i - \delta D_i\right)^2
\end{align*}

Replacing $\delta$ by its value in the population ($\Delta^Y_{TT}=\alpha_1-\alpha_0+(\beta_1-\beta_0)'\esp{X_i|D_i=1}$), using Theorem \@ref(thm:TTff), we can easily show that the remaining parameters can be obtained by two separate optimizations:

\begin{align*}
(\hat\alpha_0,\hat\beta_0) & = \arg\min_{\alpha_0,\beta_0} \frac{1}{N}\sum_{i=1}^N(1-D_i)\left(Y_i-\alpha_0 - \beta_0'X_i \right)^2\\
(\hat\alpha_1,\hat\beta_1) & = \arg\min_{\alpha_1,\beta_1} \frac{1}{N}\sum_{i=1}^ND_i\left(Y_i-\alpha_1 - \beta_1'X_i \right)^2
\end{align*}

By Theorem \@ref(thm:LinearCEF), these parameters are also identified in the population by the OLS estimator.
We now write $\tilde{Y}_i=(1-D_i)\tilde{Y}_i^0+D_i\tilde{Y}_i^1$, with:

\begin{align*}
  \tilde{Y}_i^0 & = Y_i-\beta_0'(X_i-\bar{X}_1) = \alpha_0+\beta_0'\bar{X}_1 +U_i^0 \\
  \tilde{Y}_i^1 & = Y_i-\beta_1'(X_i-\bar{X}_1) = \alpha_1+\beta_1'\bar{X}_1 +U_i^1,
\end{align*}

with $\bar{X}_1=\frac{\sum_{i=1}^ND_iX_i}{\sum_{i=1}^ND_i}$ in the sample and $\bar{X}_1=\esp{X_i|D_i=1}$ in the population.
$U_i^1$ and $U_i^0$ are mean-zero noise terms independent from $X_i$ and $D_i$ by Assumptions \@ref(hyp:CIA), \@ref(hyp:paramff0) and \@ref(hyp:paramff1).

Now, let's estimate the following regression by OLS:

\begin{align*}
  \tilde{Y}_i & = \alpha + \delta D_i + U_i \\
              & = \alpha_0+\beta_0'\bar{X}_1 +(\alpha_1-\alpha_0+(\beta_1-\beta_0)'\bar{X}_1)D_i + (1-D_i)U_i^0+D_iU_i^1
\end{align*}

$\delta^{OLS}$ estimates the treatment effect on the treated.
It is also equal to the $\Delta^Y_{WWOLSX}$ estimator (since it is a combination of the same OLS parameters).
Using Lemma \@ref(lem:WWOLS), we know that $\delta^{OLS}$ is the With/Without estimator applied to $\tilde{Y}_i$.
Using Assumptions \@ref(hyp:fullrank), \@ref(hyp:iidX) and \@ref(hyp:finitevarX), Lemma \@ref(lem:asymWW) implies that:

\begin{align*}
  \sqrt{N}(\hat{\delta}^{OLS}-\Delta^Y_{TT}) &  \stackrel{d}{\rightarrow}
  \mathcal{N}\left(0,\frac{\var{\tilde{Y}_i^1|D_i=1}}{\Pr(D_i=1)}+\frac{\var{\tilde{Y}_i^0|D_i=0}}{1-\Pr(D_i=1)}\right).
\end{align*}

By construction, and using Assumptions \@ref(hyp:paramff0) and \@ref(hyp:paramff1), $\var{\tilde{Y}_i^d|D_i=d}=\var{Y_i^d|X_i,D_i=d}$.

**Clarify what $\var{Y_i^d|X_i,D_i=d}$ is exactly and what happens when it depends on $X_i$**


