---
title: "Statistical Tools for Causal Inference"
author: "Sylvain Chabé-Ferret"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
#output: bookdown::gitbook
documentclass: book
#bibliography: [book.bib, packages.bib]
#biblio-style: apalike
#link-citations: yes
github-repo: chabefer/STCI
description: "This is an open source collaborative book."
---

# Introduction {-}

Tools of causal inference are the basic statistical building block behind most scientific results.
It is thus extremely useful to have an open source collectively aggreed upon resource presenting and assessing them, as well as listing the current unresolved issues.
The content of this book covers the basic theoretical knowledge and technical skills required for implementing staistical methods of causal inference.
This means:

* Understanding of the basic language to encode causality,
* Knowledge of the fundamental problems of inference and the biases of intuitive estimators,
* Understanding of how econometric methods recover treatment effects,
* Ability to compute these estimators along with an estimate of their precision using the statistical software R.

This book is geared for teaching causal inference to graduate students that want to apply statistical tools of causal inference.
The demonstration of theoretical results are provided, but the final goal is not to have students reproduce them, but mostly to enable them to grasp a better understanding of the fundations for the tools that they will be using.
The focus is on understanding the issues and solutions more than understanding the maths that are behind, even though the maths are there and are used to convey the notions rigorously.
All the notions and estimators are introduced using a numerical example and simulations, so that each notion is illustrated and appears more intuitive to the students. 
The second version of this book will contain examples using real applications.
The third version will contain exercises.

This book is written in Rmarkdown using the bookdown package.
It is available both as a [web-book](https://chabefer.github.io/STCI/) and as a [pdf book](https://chabefer.github.io/STCI/STCI.pdf).

This book is a collaborative effort that is part of the [Social Science Knowledge Accumulation Initiative (SKY)](https://chabefer.github.io/SKY/). 
The code behind this book is publically available on GitHub and you can propose corrections and updates.
How to make contributions to this book is explained on the [SKY website](https://chabefer.github.io/SKY/tutoSTCI.html).
Do not hesitate to make suggestions, modifications and extensions. 
This way this book will grow and become the living open source collaborative reference for methodological work that it could be.
